import type { GuideCategory, GuideChapter } from "./types";
import { guideOperationsChapters } from "./operations";

export const GUIDE_UPDATED_AT = "2026-09-11";
export const GUIDE_CONTENT_VERSION = "1.0.0";

export const guideCategories: GuideCategory[] = [
  { id: "zaciname", title: "Začíname", description: "Prvý prístup, orientácia a pripravené pracovisko.", icon: "start" },
  { id: "telefonovanie", title: "Telefonovanie počas služby", description: "Prijať hovor, postarať sa o čakajúcich a bezpečne odísť na pauzu.", icon: "phone" },
  { id: "pripady", title: "Práca s prípadmi", description: "Od prvého kontaktu cez zabezpečenie pomoci až po dokončenie.", icon: "cases" },
  { id: "nastavenia", title: "Nastavenie telefonovania", description: "Pochopte cestu hovoru a nastavte skupiny, kroky aj pracovný čas.", icon: "settings" },
  { id: "prevadzka", title: "Organizácia prevádzky", description: "Smeny, vozidlá, kontakty, reporty a prístupy kolegov.", icon: "team" },
  { id: "pomoc", title: "Keď potrebujete pomoc", description: "Riešenia bežných problémov, slovník a pracovné kontrolné zoznamy.", icon: "help" },
];

/** General product guidance; names, numbers and timings in illustrations are training examples. */
export const guideChapters: GuideChapter[] = [
  {
    slug: "prihlasenie", title: "Prvý prístup a prihlásenie", description: "Ako aktivovať účet, prihlásiť sa a obnoviť zabudnuté heslo.", categoryId: "zaciname", audience: "all", minutes: 4,
    keywords: ["účet", "login", "heslo", "pozvánka", "obnova", "prístup", "odhlásenie", "rola"],
    prerequisites: ["Vlastný účet pridelený správcom a prístup k jeho e-mailovej schránke.", "Adresa aplikácie, ktorú vám poskytol správca."],
    sections: [
      { id: "prvy-pristup", title: "Keď aplikáciu otvárate prvýkrát", paragraphs: ["Každý dispečer pracuje pod vlastným účtom. Aplikácia podľa neho priraďuje hovory, prípady a úlohy a určuje, ktoré nastavenia smiete upravovať."], steps: [
        { id: "otvorit-pozvanku", title: "Otvorte pozvánku", text: "V e-maile od správcu otvorte odkaz na nastavenie hesla. Ak ho nenájdete, skontrolujte aj nevyžiadanú poštu." },
        { id: "nastavit-heslo", title: "Nastavte si heslo", text: "Vyplňte Nové heslo a Zopakovať heslo a stlačte Nastaviť heslo. Riaďte sa požiadavkami uvedenými pri formulári.", result: "Aplikácia potvrdí nastavenie hesla alebo zobrazí konkrétny dôvod, prečo ho nemohla uložiť." },
        { id: "otvorit-aplikaciu", title: "Pokračujte do aplikácie", text: "Otvorte pridelenú adresu aplikácie. Ak sa zobrazí Prihlásenie, použite e-mail z pozvánky a nové heslo." },
      ] },
      { id: "bezne-prihlasenie", title: "Bežné prihlásenie", steps: [
        { id: "vyplnit-udaje", title: "Vyplňte Email a Heslo", text: "Použite údaje svojho pracovného účtu. Pri kopírovaní hesla si dajte pozor na medzeru navyše." },
        { id: "prihlasit-sa", title: "Stlačte Prihlásiť sa", text: "Počkajte na otvorenie pracovnej obrazovky. Ak sa zobrazí chyba, opravte údaje podľa hlášky.", result: "Vidíte aplikáciu pod svojím menom. Na prijímanie hovorov ešte skontrolujte telefón a dostupnosť." },
      ], screenshotIds: ["login"] },
      { id: "obnova-hesla", title: "Keď ste zabudli heslo", steps: [
        { id: "zabudnute-heslo", title: "Otvorte Zabudnuté heslo", text: "Na prihlasovacej obrazovke zadajte e-mail svojho účtu a odošlite žiadosť o obnovu." },
        { id: "pouzit-novy-odkaz", title: "Použite doručený odkaz", text: "Otvorte nový e-mail, nastavte a zopakujte heslo. Ak odkaz už neplatí, vyžiadajte si nový alebo kontaktujte správcu.", result: "Pri ďalšom prihlásení použijete nové heslo." },
      ], note: { tone: "info", title: "Potvrdenie odoslania neoveruje existenciu účtu", text: "Správa o odoslaní obnovy sama nepotvrdzuje, že je e-mail v aplikácii zaregistrovaný. Ak nič nepríde, správca skontroluje adresu a stav účtu." } },
      { id: "roly", title: "Prečo kolega vidí iné možnosti", table: { headers: ["Rola v aplikácii", "Čo znamená pri práci s návodom"], rows: [
        ["Dispečer", "Každodenná práca s hovormi, prípadmi a úlohami; nastavenia vlastného telefónu."],
        ["Senior dispečer", "Dispečerská práca s rozšíreniami podľa oprávnení jednotlivých funkcií."],
        ["Manažér", "Aj správa skupín, plánov a ďalších prevádzkových nastavení telefonovania."],
        ["Admin", "Aj vyhradené organizačné nastavenia a správa prístupov."],
      ] }, paragraphs: ["Označenie kapitoly Manažér / Admin upozorňuje na rolu potrebnú na uloženie opisovaných zmien. Niektoré nastavenia si dispečer môže prezerať iba na čítanie. Reporty sú dostupné aj dispečerom."] },
      { id: "odhlasenie", title: "Odhlásenie na konci práce", paragraphs: ["Najprv dokončite alebo odovzdajte hovor a rozpracovanú prácu. V stave telefónu použite Odhlásiť z telefónie a v menu účtu sa odhláste z aplikácie. Odhlásenie z telefónie ukončí dostupnosť na hovory; prístup do ostatných častí aplikácie tým nestratíte."], note: { tone: "important", title: "Nezatvárajte okno počas hovoru", text: "Pred zatvorením aplikácie skontrolujte, že nemáte aktívny hovor ani neuložené údaje. Pri odovzdaní počítača ďalšiemu kolegovi použite jeho vlastný účet." } },
    ], related: ["priprava-na-sluzbu", "orientacia", "riesenie-problemov"], sources: ["src/components/auth/MotoristLogin.tsx", "src/components/auth/SetPasswordForm.tsx", "src/components/auth/ForgotPasswordForm.tsx", "src/components/dispatch/UserAccessSettings.tsx", "src/components/dispatch/HeaderPhoneStatusMenu.tsx"],
  },
  {
    slug: "orientacia", title: "Orientácia v aplikácii", description: "Kde nájdete prípady, telefón, menu a nástroje na každodennú prácu.", categoryId: "zaciname", audience: "all", minutes: 4,
    keywords: ["nástenka", "menu", "navigácia", "prehľad", "mobil", "pripnúť", "ústredňa", "nástroje"], prerequisites: ["Ste prihlásený do aplikácie."],
    sections: [
      { id: "pracovna-obrazovka", title: "Začnite Nástenkou", paragraphs: ["Nástenka spája pracovný prehľad, prípady a nástroje. V hornej časti kontrolujte vlastný telefón, dostupnosť, čakáreň a upozornenia. V pracovnej ploche otvárate prípady alebo mapu a podľa potreby úlohy či poznámky.", "Rozloženie sa môže líšiť podľa šírky okna a pripnutých položiek. Pri hľadaní funkcie sa orientujte podľa názvu, nielen podľa polohy na obrázku."], screenshotIds: ["overview"] },
      { id: "kam-ist", title: "Čo hľadať v Menu", table: { headers: ["Oblasť", "Kedy ju otvoriť"], rows: [
        ["Nástenka", "Chcete mať počas služby pracovný prehľad a rýchly prístup k nástrojom."],
        ["Prípady", "Hľadáte konkrétny zásah alebo prechádzate aktívne a historické prípady."],
        ["Ústredňa", "Sledujete pracovisko telefonovania, hovory a ich históriu."],
        ["Úlohy a Poznámky", "Potrebujete termín, odovzdať úlohu alebo uložiť pracovné poznámky."],
        ["Dochádzka, Flotila a Reporty", "Riešite smeny, techniku alebo prehľad výsledkov."],
        ["Nastavenia", "Pripravujete svoj telefón alebo upravujete prevádzku podľa svojej roly."],
      ] } },
      { id: "pripnute-polozky", title: "Upravte si rýchly prístup", steps: [
        { id: "otvorit-menu", title: "Otvorte Menu", text: "Nájdite obrazovku, ktorú používate často, a otvorte ju podľa názvu." },
        { id: "pripnut", title: "Použite pripnutie pri položke", text: "Ak pri položke vidíte ovládanie pripnutia, pridajte ju do rýchlej navigácie. Nepotrebnú položku môžete rovnakým ovládaním odopnúť.", result: "Najčastejšie používanú obrazovku otvoríte bez prechádzania celého menu." },
      ] },
      { id: "telefon-zostava-po-ruke", title: "Telefonovanie pri práci s prípadom", paragraphs: ["Pri prichádzajúcom alebo aktívnom hovore sledujte panel hovoru. Môžete sa venovať prípadu a zároveň ovládať hovor. Čakáreň je dostupná aj mimo pracoviska Ústredne, takže kvôli čakajúcemu volajúcemu nemusíte opúšťať rozpracovaný prípad.", "Pri prechode z rozpracovaného formulára rešpektujte upozornenie na uloženie. Telefón v druhom okne môže prevziať iba jedno pracovné okno; pomoc otvárajte odkazom Návod."] },
      { id: "mobilna-navigacia", title: "Na mobile používajte Menu a Viac", paragraphs: ["Na užšej obrazovke sa panely zobrazujú po jednom a časť navigácie sa presunie do dolnej lišty alebo Menu. Doplnkové akcie aktívneho hovoru otvoríte cez Viac. Vždy si najprv všimnite názov otvorenej obrazovky.", "Otvorenie webovej aplikácie na mobile nie je to isté ako prijímanie pracovných hovorov na osobné telefónne číslo. Spôsob prijímania si zvoľte v Môj telefón. Pri webovom volaní nechajte aplikáciu otvorenú; správanie na pozadí závisí od zariadenia a povolení."], screenshotIds: ["menu-mobile"] },
    ], related: ["priprava-na-sluzbu", "pripad", "moj-telefon"], sources: ["src/components/dispatch/DispatchConsole.tsx", "src/components/dispatch/navigation-preferences.ts", "src/components/dispatch/PhoneBar.tsx", "src/components/dispatch/CallQueuePanel.tsx"],
  },
  {
    slug: "priprava-na-sluzbu", title: "Pripravenie na službu", description: "Skontrolujte zvuk a telefón a vedome sa sprístupnite pre pracovné hovory.", categoryId: "zaciname", audience: "all", minutes: 5,
    keywords: ["služba", "mikrofón", "pripojenie", "dostupný", "slúchadlá", "notifikácie", "zvuk", "pripravenosť"], prerequisites: ["Vlastný prihlásený účet a funkčné internetové pripojenie.", "Pri volaní v aplikácii pripojené slúchadlá alebo reproduktor a mikrofón."],
    sections: [
      { id: "tri-samostatne-veci", title: "Prihlásenie, smena a dostupnosť sú tri veci", table: { headers: ["Stav", "Čo potvrdzuje"], rows: [["Prihlásenie", "Môžete pracovať v aplikácii pod svojím účtom."], ["Naplánovaná smena", "Ste uvedený v pláne dochádzky."], ["Dostupný telefón", "Ste pripravený prijímať ponuky hovorov, ak je pripravené aj zvolené zariadenie."]] }, paragraphs: ["Samotné prihlásenie ani naplánovaná smena nepotvrdzujú, že vám teraz môže zazvoniť telefón. Potrebujete správne prijímanie hovorov, dostupnosť a funkčné spojenie."] },
      { id: "kontrola-zvuku", title: "Skontrolujte mikrofón a výstup zvuku", steps: [
        { id: "pripojit-sluchadla", title: "Pripojte pracovné slúchadlá", text: "V ovládaní počítača alebo telefónu skontrolujte, že je zvolený správny mikrofón a počujete systémový zvuk." },
        { id: "skontrolovat-mikrofon", title: "Otvorte stav telefónu a Skontrolovať mikrofón", text: "Povoľte prehliadaču mikrofón a počkajte na výsledok. Táto kontrola nevytáča číslo ani nevytvára nahrávku.", result: "Pri tlačidle sa zobrazí výsledok kontroly alebo pokyn na opravu povolenia." },
        { id: "vybrat-vystup", title: "Overte Kam ide zvuk hovoru", text: "V Nastavenia → Telefonovanie → Môj telefón skontrolujte zvukový výstup. Ak výber zariadenia prehliadač neponúka, zmeňte ho v systéme. Po odpojení slúchadiel môže zvuk prejsť na predvolené zariadenie." },
      ], screenshotIds: ["phone-settings"] },
      { id: "spristupnit-telefon", title: "Pripravte telefón a zapnite dostupnosť", steps: [
        { id: "overit-rezim", title: "Overte spôsob prijímania", text: "V Môj telefón skontrolujte, či používate Telefón v aplikácii alebo Prijímam na osobnom mobile. Pri osobnom mobile overte aj uložené číslo." },
        { id: "overit-pripojenie", title: "Skontrolujte stav telefónu", text: "Pri volaní v prehliadači musí byť telefón pripojený v okne, v ktorom pracujete. Ak je v inom okne, vedome použite Prevziať telefón do tohto okna." },
        { id: "zapnut-dostupnost", title: "Zvoľte Dostupný", text: "V menu stavu telefónu zvoľte Dostupný alebo v Môj telefón tlačidlo Som dostupný.", result: "Zobrazená dostupnosť sa zmení. Ak zmena zlyhá, riaďte sa chybou; samotné kliknutie ešte úspech nepotvrdzuje." },
      ] },
      { id: "upozornenia-a-skuska", title: "Upozornenia a prvá skúška", paragraphs: ["Otvorte upozornenia a prečítajte nevybavené položky z predošlej služby. Ak používate systémové upozornenia na hovory, povoľte ich pre aplikáciu aj v nastaveniach zariadenia. Vypnutý zvuk, režim Nerušiť alebo úspora energie môžu ovplyvniť, čo si všimnete.", "Pri prvom nastavení si s kolegom dohodnite krátky skúšobný hovor. Overte, že sa navzájom počujete a že po zložení vidíte očakávaný stav. Skúšobný hovor je skutočné volanie na vybrané číslo; údaj na obrázku je len príklad."], screenshotIds: ["notifications"] },
      { id: "prva-pracovna-kontrola", title: "Pred prvým hovorom", bullets: ["Pozrite, kto ďalší je dostupný a kto preberá službu.", "Skontrolujte čakáreň, spätné volania a vlastné úlohy po termíne.", "Otvorte odovzdávané prípady a prečítajte posledné poznámky.", "Nechajte pracovné okno otvorené a skontrolujte, že telefón neprevzalo iné okno." ] },
    ], related: ["moj-telefon", "prijatie-a-zacatie-hovoru", "riesenie-problemov"], sources: ["src/components/dispatch/HeaderPhoneStatusMenu.tsx", "src/components/dispatch/MyPhonePanel.tsx", "src/components/dispatch/HeaderNotificationMenu.tsx", "src/components/dispatch/AttendanceModule.tsx"],
  },
  {
    slug: "prijatie-a-zacatie-hovoru", title: "Prijatie a začatie hovoru", description: "Prijmite klienta, zavolajte z aplikácie a priraďte rozhovor k správnemu prípadu.", categoryId: "telefonovanie", audience: "all", minutes: 5,
    keywords: ["prichádzajúci", "odchádzajúci", "prijať", "odmietnuť", "vytáčanie", "zavolať", "linka", "priradenie hovoru"], prerequisites: ["Telefón je pripravený na zvolený spôsob prijímania.", "Na automatické prichádzajúce ponuky ste Dostupný."],
    sections: [
      { id: "prichadzajuci-hovor", title: "Keď vám zvoní telefón", steps: [
        { id: "precitat-ponuku", title: "Pozrite číslo a linku", text: "V ponuke prichádzajúceho hovoru skontrolujte číslo alebo meno volajúceho a štítok linky. Podľa linky zistíte, ktorú službu klient kontaktoval." },
        { id: "prijat", title: "Stlačte Prijať", text: "Počkajte na spojenie a začnite rozhovor, keď sa zobrazí aktívny hovor. Pri prijímaní na osobnom mobile zdvihnite volanie na tomto mobile.", result: "Hovor obsluhujete vy. Ak vám bol ponúkaný spoločne s kolegami, ich ponuka sa skončí po úspešnom prijatí." },
        { id: "overit-klienta", title: "Overte, čo klient potrebuje", text: "Zistite, či ide o nový zásah alebo už riešený prípad. Overte použiteľné spätné číslo, vozidlo, miesto a požadovanú pomoc." },
      ], screenshotIds: ["incoming-call"] },
      { id: "odmietnutie", title: "Keď hovor nemôžete prijať", paragraphs: ["Odmietnuť odmietne vašu ponuku hovoru. Neznamená to, že je potreba klienta vybavená; ďalší postup riadi plán linky a dostupnosť ostatných. Ak nebudete prijímať ďalšie hovory, po skončení prebiehajúcich akcií nastavte pauzu alebo sa odhláste z telefónie.", "Ponuka môže zmiznúť aj preto, že ju prijal kolega alebo volajúci zložil. Nevytvárajte nový hovor len preto, že sa pôvodné okno zavrelo; najprv skontrolujte aktuálny stav."] },
      { id: "odchadzajuci-hovor", title: "Ako zavolať klientovi", steps: [
        { id: "overit-ciel", title: "Vyberte správne telefónne číslo", text: "Použite volanie pri kontakte v prípade alebo adresári, prípadne zadajte číslo v telefóne. Pri viacerých kontaktoch overte, komu voláte. Pri ručnom zadaní použite aj medzinárodnú predvoľbu." },
        { id: "overit-linku", title: "Skontrolujte odchádzajúcu linku", text: "Pred volaním overte, z ktorého pracovného čísla voláte. Predvolenú Odchádzajúcu linku nastavíte v Môj telefón; toto číslo sa zobrazuje volanému." },
        { id: "zavolat", title: "Spustite volanie a počkajte", text: "Stlačte volanie raz a sledujte jeho stav. Opätovným klikaním počas vytáčania neurychlíte spojenie.", result: "Po prijatí druhou stranou sa zobrazuje aktívny hovor. Neúspešný pokus nie je potvrdením kontaktovania klienta." },
      ] },
      { id: "hovor-a-pripad", title: "Prepojte rozhovor s prípadom", steps: [
        { id: "najst-kartu", title: "Otvorte existujúci prípad alebo vytvorte nový", text: "Najprv overte, či už prípad existuje. Pri novej požiadavke použite vytvorenie prípadu z hovoru alebo Nový prípad." },
        { id: "priradit-hovor", title: "Potvrďte Priradiť k prípadu", text: "V sekcii Priradiť prichádzajúci hovor vyberte správny hovor a potvrďte priradenie. Samotná zhoda telefónneho čísla ho k otvorenej karte automaticky nepripojí.", result: "Hovor sa eviduje pri zvolenom prípade. Ak tlačidlo ešte čaká na zápis hovoru, chvíľu počkajte na sprístupnenie." },
      ], screenshotIds: ["case-detail"] },
      { id: "ukoncit-hovor", title: "Ukončite rozhovor a doplňte výsledok", paragraphs: ["Zhrňte dohodu a použite Zavesiť. Do prípadu alebo úlohy zapíšte výsledok a ďalší krok. Ak začne dopisovanie, dokončite záznam v tomto čase. Zavretie karty prípadu ani prepnutie obrazovky nenahrádza ukončenie hovoru."] },
    ], related: ["pocas-hovoru", "pripad", "spatne-hovory"], sources: ["src/components/dispatch/PhoneBar.tsx", "src/components/dispatch/phone-bar-model.ts", "src/components/dispatch/CaseDetail.tsx", "src/components/dispatch/DispatchConsole.tsx", "src/components/dispatch/MyPhonePanel.tsx"],
  },
  {
    slug: "pocas-hovoru", title: "Čo možno robiť počas hovoru", description: "Rozdiel medzi mikrofónom, podržaním, čakárňou a prepojením kolegovi.", categoryId: "telefonovanie", audience: "all", minutes: 7,
    keywords: ["mikrofón", "stlmiť", "podržať", "pokračovať", "prepojenie", "konzultácia", "transfer", "konferencia", "DTMF"], prerequisites: ["Máte aktívny spojený hovor.", "Na konzultáciu alebo prepojenie potrebujete dostupného kolegu alebo povolené cieľové číslo."],
    sections: [
      { id: "vybrat-spravnu-akciu", title: "Vyberte akciu podľa toho, čo potrebujete", table: { headers: ["Ovládanie", "Čo tým urobíte"], rows: [["Mikrofón", "Stíšite svoj mikrofón. Hovor zostáva u vás a klienta ďalej počujete."], ["Podržať / Pokračovať", "Dočasne prerušíte rozhovor s klientom a potom sa k nemu vrátite; hovor zostáva vašou prácou."], ["Do čakárne", "Odložíte spojeného klienta do spoločnej čakárne, odkiaľ ho môže prevziať dispečer."], ["Prepojiť", "Začnete priame odovzdanie hovoru zvolenému cieľu bez predchádzajúcej konzultácie."], ["Konzultovať", "Najprv hovoríte s kolegom a až potom sa rozhodnete prepojenie dokončiť alebo zrušiť."]] }, screenshotIds: ["active-call"] },
      { id: "mikrofon-a-podrzanie", title: "Krátke prerušenie rozhovoru", paragraphs: ["Ak potrebujete na okamih hovoriť mimo hovoru, stlmte mikrofón a pred návratom ho znova zapnite. Stlmenie neodošle klienta ku kolegovi ani do čakárne.", "Pri dlhšom overovaní klientovi povedzte, že ho na chvíľu podržíte. Stlačte Podržať a po overení Pokračovať. Počas podržania klient nie je súčasťou vášho rozhovoru; zvuk čakania závisí od nastavenia linky. Pred pokračovaním skontrolujte aj vlastný mikrofón."] },
      { id: "odlozit-do-cakarne", title: "Odloženie do spoločnej čakárne", steps: [
        { id: "oznamit-cakanie", title: "Povedzte klientovi, čo bude nasledovať", text: "Vysvetlite, že zostane na linke a hovor prevezmete vy alebo kolega. Dôležité informácie zapíšte k prípadu." },
        { id: "do-cakarne", title: "Stlačte Do čakárne", text: "Počkajte na potvrdenie odloženia; ak sa objaví chyba, hovor nepovažujte za odovzdaný.", result: "Klient zostáva spojený a v čakárni sa zobrazuje ako Odložený hovor s údajmi o odložení." },
        { id: "dohodnut-prevzatie", title: "Dohodnite prevzatie s kolegom", text: "Oznámte kolegovi, ktorý hovor čaká a k akému prípadu patrí. Sledujte čas odloženia, aby klient nezostal bez ďalšej pozornosti." },
      ] },
      { id: "priame-prepojenie", title: "Priame prepojenie", steps: [
        { id: "otvorit-prepojenie", title: "Stlačte Prepojiť", text: "Na mobile môže byť akcia pod Viac. Otvorí sa výber dostupných kolegov a poľa Externé číslo." },
        { id: "vybrat-ciel", title: "Vyberte kolegu alebo číslo", text: "Kliknutie na dostupného kolegu spustí prepojenie. Pri externom čísle skontrolujte číslo a potvrďte tlačidlo vo formulári." },
        { id: "overit-vysledok-prepojenia", title: "Sledujte výsledok", text: "Počkajte na zmenu stavu. Pri chybe si overte, či zostáva klient vo vašom hovore, a pokračujte v jeho obsluhe.", result: "Po úspešnom prepojení klient pokračuje so zvoleným cieľom. Výber nedostupného kolegu aplikácia nepovolí." },
      ], screenshotIds: ["transfer"] },
      { id: "konzultacia", title: "Prepojenie s krátkou konzultáciou", steps: [
        { id: "spustit-konzultaciu", title: "Zvoľte Konzultovať a kolegu", text: "Klient počká, kým sa spojíte s kolegom. Počkajte, kým konzultačný hovor skutočne prijme." },
        { id: "odovzdat-kontext", title: "Vysvetlite prípad", text: "Povedzte číslo prípadu, situáciu klienta a čo má kolega vybaviť. Klient tento konzultačný rozhovor nepočuje." },
        { id: "dokoncit-prepojenie", title: "Použite Dokončiť prepojenie", text: "Keď kolega súhlasí s prevzatím, dokončite prepojenie.", result: "Klient a kolega pokračujú v rozhovore a vy už nie ste jeho obsluhou." },
        { id: "zrusit-konzultaciu", title: "Ak sa neodovzdáva, použite Zrušiť konzultáciu", text: "Konzultáciu ukončite a skontrolujte návrat ku klientovi. Podľa zobrazeného stavu použite Pokračovať." },
      ] },
      { id: "dalsie-moznosti", title: "Ďalšie možnosti závisia od hovoru", paragraphs: ["Klávesnica počas hovoru slúži na zadanie číslic napríklad do telefonického menu druhej strany. Nemení telefónne číslo hovoru.", "Ak sa zobrazí Pridať účastníka, Odísť z hovoru alebo ovládanie dohľadu či nahrávania, dostupnosť sa riadi konkrétnym hovorom, nastavením a vašou rolou. Tieto rozšírenia používajte po zaškolení vo vašej prevádzke. Sivé tlačidlo alebo chýbajúca akcia nie sú dôvodom opakovane klikať na iné ovládanie."], note: { tone: "important", title: "Zavesiť nie je odovzdanie", text: "Na odovzdanie klienta použite prepojenie. Pri konzultácii nezamieňajte Zavesiť, Zrušiť konzultáciu a Dokončiť prepojenie; sledujte, s kým práve hovoríte." } },
    ], related: ["cakaren", "pauza-a-zastupovanie", "riesenie-problemov"], sources: ["src/components/dispatch/PhoneBar.tsx", "src/components/dispatch/phone-bar-model.ts", "src/components/dispatch/CallTransferPicker.tsx", "src/server/telephony/state/transitions.ts"],
  },
  {
    slug: "cakaren", title: "Čakáreň hovorov", description: "Kto stále čaká na linke, ako sa mu ponúka spojenie a ako ho prevziať.", categoryId: "telefonovanie", audience: "all", minutes: 6,
    keywords: ["čakáreň", "fronta", "queue", "čakanie", "prevziať", "odložený hovor", "parkovanie"], prerequisites: ["Ste prihlásený a máte pripravený telefón.", "Na prevzatie nesmiete byť zaneprázdnený nekompatibilnou akciou; riaďte sa dôvodom pri tlačidle."],
    sections: [
      { id: "co-je-cakaren", title: "V čakárni je klient stále na linke", paragraphs: ["Čakáreň zobrazuje prichádzajúcich klientov, ktorí ešte čakajú na dispečera, aj hovory vedome odložené cez Do čakárne. Volajúci ešte nezložil. Preto treba sledovať čakáreň aj pri práci s prípadmi.", "Požiadavka na spätné volanie je iná: klient už nemusí byť na linke a dispečer mu bude volať novým hovorom. Tlačidlo Prevziať pri spätnej požiadavke len určuje zodpovednosť; v čakárni slúži na prevzatie živého hovoru."], screenshotIds: ["queue"] },
      { id: "stavy-v-cakarni", title: "Ako čítať kartu čakajúceho", table: { headers: ["Údaj alebo stav", "Čo z neho zistíte"], rows: [["Meno / telefón a linka", "Kto čaká a na ktorú službu zavolal."], ["Čas čakania", "Ako dlho už hovor trvá v evidovanom čakaní; pomôže určiť, komu venovať pozornosť."], ["Zvoní: meno", "Hovor sa práve ponúka uvedenému operátorovi. Ešte to neznamená, že ho prijal."], ["Čaká na pridelenie", "Klient čaká na ďalšiu možnosť spojenia."], ["Odložený hovor", "Hovor niekto odložil do čakárne. Pri ňom sledujte informáciu o odložení a zostávajúcom čase."]] } },
      { id: "rucne-prevzatie", title: "Ako prevziať konkrétny čakajúci hovor", steps: [
        { id: "otvorit-cakaren", title: "Otvorte Čakáreň hovorov", text: "Použite ovládanie čakárne v hlavičke alebo jej panel na pracovisku Ústredne. Na mobile ho hľadajte medzi dostupnými panelmi telefonovania." },
        { id: "vybrat-cakajuceho", title: "Vyberte konkrétneho klienta", text: "Skontrolujte číslo, linku a čas. Pri odloženom hovore si prečítajte súvisiaci prípad alebo dohodu s kolegom." },
        { id: "prevziat-cakajuceho", title: "Stlačte Prevziať", text: "Počkajte na úspešné prevzatie a prípadnú ponuku vo vašom telefóne. Keď sa zobrazí prichádzajúca ponuka, prijmite ju.", result: "Až po spojení vidíte klienta vo vlastnom aktívnom hovore. Ak hovor medzitým prevzal kolega alebo klient zložil, prevzatie už nie je možné." },
      ] },
      { id: "automaticke-ponukanie", title: "Čo robí automatické ponúkanie", paragraphs: ["Pri vhodnej dostupnosti systém ponúka čakajúce hovory operátorom. Ponuka sa automaticky nezdvihne: dispečer musí hovor prijať. Priebeh závisí od plánu linky, dostupnosti a voľnej kapacity.", "Opakovaná ponuka z automatickej čakárne neznamená, že sa pri každom pokuse znovu vytáčajú všetky externé záložné čísla z plánu. Sľub klientovi preto nezakladajte iba na poradí externých členov v skupine."] },
      { id: "koniec-cakania", title: "Čakanie má svoj koniec", paragraphs: ["Čakáreň aj odloženie majú nastavený časový limit. Po jeho dosiahnutí systém ponúkne spätné volanie, ak má použiteľné spätné číslo. Počas čakania môže klient po vypočutí príslušnej výzvy požiadať o spätný hovor klávesou 1. Pri skrytom alebo nepoužiteľnom čísle sa takáto možnosť nemusí ponúknuť.", "Limit Maximum v čakárni (min) nastavuje Admin v Nastavenia → Telefonovanie → Bezpečnosť. Nový limit sa týka hovorov, ktoré do čakárne prídu po uložení; už čakajúci pokračujú podľa svojho pôvodného limitu. Číslica počas čakania je samostatná voľba a nemusí byť rovnaká ako číslica v úvodnom IVR menu."], note: { tone: "important", title: "Chýbajúci hovor treba skontrolovať", text: "Keď klient zmizne z čakárne, nemusí byť vybavený. Mohol zložiť alebo prejsť do spätných volaní. Overte stav v Ústredni a v zozname spätných požiadaviek." } },
    ], related: ["spatne-hovory", "pocas-hovoru", "plany-zvonenia"], sources: ["src/components/dispatch/CallQueuePanel.tsx", "src/components/dispatch/useTelephonyConsole.ts", "src/server/telephony/state/transitions.ts", "src/components/dispatch/settings/TelephonySettingsPanel.tsx"],
  },
  {
    slug: "spatne-hovory", title: "Neprijaté a spätné hovory", description: "Prevezmite zodpovednosť za zavolanie, kontaktujte klienta a uzavrite požiadavku.", categoryId: "telefonovanie", audience: "all", minutes: 5,
    keywords: ["callback", "spätné volanie", "neprijatý", "zmeškaný", "vybavené", "overené číslo", "po termíne"], prerequisites: ["Máte prístup k panelu spätných volaní.", "Na zavolanie potrebujete pripravený telefón a použiteľné cieľové číslo."],
    sections: [
      { id: "povod-poziadavky", title: "Najprv rozlíšte, prečo záznam vznikol", paragraphs: ["Klient môže výslovne požiadať o spätné volanie v hlasovom menu alebo počas čakania. V zozname môžu byť aj neprijaté hovory, pri ktorých klient takúto požiadavku nevyslovil. Všímajte si označenie pôvodu pri každej položke.", "Obidva typy si zaslúžia posúdenie, ale pri hovore nehovorte klientovi, že žiadal spätné volanie, ak to záznam nepotvrdzuje. Ak už vec vybavil kolega, najprv overte históriu."], screenshotIds: ["callbacks"] },
      { id: "prevziat-zodpovednost", title: "Prevezmite zodpovednosť", steps: [
        { id: "skontrolovat-poziadavku", title: "Pozrite číslo, linku a čas", text: "Skontrolujte aj označenie Po termíne a meno kolegu, ak už má položku prevzatú. Otvorte súvisiaci prípad, ak existuje." },
        { id: "prevziat-poziadavku", title: "Stlačte Prevziať", text: "Tým oznámite, že sa požiadavke venujete vy.", result: "Požiadavka je prevzatá a zobrazuje sa zodpovednosť. Táto akcia ešte nevytáča telefónne číslo." },
      ] },
      { id: "kontaktovat-klienta", title: "Zavolajte a zaznamenajte výsledok", steps: [
        { id: "zavolat-spat", title: "Stlačte Zavolať", text: "Overte cieľ a sledujte vytáčanie. Ak systém ponúkne overené náhradné číslo, prečítajte si pôvodné aj náhradné číslo a potvrďte iba správny kontakt." },
        { id: "zapisat-vysledok", title: "Zapíšte výsledok rozhovoru", text: "Do prípadu alebo úlohy zaznamenajte, čo klient potrebuje a čo ste dohodli. Pri neúspešnom pokuse zachovajte potrebu ďalšieho kontaktu a dohodnite termín opakovania." },
        { id: "oznacit-vybavene", title: "Po dokončení zvoľte Vybavené", text: "Vybavenie potvrďte až po tom, čo je požiadavka vyriešená.", result: "Požiadavka sa uzavrie. Samotné začatie volania nie je dôkazom, že ste klienta zastihli alebo mu zabezpečili pomoc." },
      ] },
      { id: "zrusit-alebo-nechat", title: "Kedy použiť Zrušiť", paragraphs: ["Zrušiť použite pre požiadavku, ktorú už netreba vybavovať, napríklad po overení duplicity alebo po potvrdení, že klient pomoc nepotrebuje. Dôvod zapíšte k príslušnej práci, aby ďalšia služba vedela, prečo sa už nevolá.", "Ak požiadavku prevzal kolega, rešpektujte uvedenú zodpovednosť. Pri potrebe odovzdania sa dohodnite; nepovažujte sivé tlačidlo za chybu len preto, že práve nemôžete zasiahnuť do cudzej položky."] },
      { id: "nepouzitelne-cislo", title: "Neznáme alebo nepoužiteľné číslo", paragraphs: ["Na skryté, neúplné alebo jednosmerné číslo sa nemusí dať zavolať späť. Aplikácia môže volanie zablokovať a vyžiadať overený náhradný kontakt. Číslo nedopĺňajte odhadom.", "Overený náhradný kontakt sa potvrdzuje pred volaním. Pôvodné číslo zostáva v histórii. Ak sa správny kontakt nedá získať, zaznamenajte túto prekážku a odovzdajte požiadavku podľa pravidiel prevádzky." ] },
    ], related: ["cakaren", "prijatie-a-zacatie-hovoru", "ulohy-a-poznamky"], sources: ["src/components/dispatch/CallbackQueuePanel.tsx", "src/lib/telephony/callback-target-client.ts", "src/lib/telephony/callback-queue.ts"],
  },
  {
    slug: "pauza-a-zastupovanie", title: "Pauza, zastupovanie a dopisovanie", description: "Odíďte na prestávku so správnym zastupovaním a po návrate sa vedome sprístupnite.", categoryId: "telefonovanie", audience: "all", minutes: 6,
    keywords: ["pauza", "prestávka", "zastupovanie", "kolega", "dopisovanie", "wrap-up", "návrat", "pripomienka"], prerequisites: ["Nemáte aktívny hovor; počas hovoru nie je zmena dostupnosti povolená.", "Viete, kto počas prestávky pokrýva službu."],
    sections: [
      { id: "pred-pauzou", title: "Pred prestávkou skontrolujte pokrytie", paragraphs: ["Najprv dokončite alebo odovzdajte aktívny hovor, rozpracované prípady a neodkladné úlohy. Pozrite, kto z kolegov je dostupný. Ak odchádza posledný dostupný operátor, hovory budú pokračovať podľa plánu do čakania alebo k nastavenej zálohe.", "Pauza blokuje automatické pracovné hovory v aplikácii aj na vašom osobnom mobile. Ak chcete počas práce prijímať na osobnom mobile, nastavuje sa to samostatne v Môj telefón a potrebujete zostať dostupný."] },
      { id: "zapnut-pauzu", title: "Ako zapnúť pauzu", steps: [
        { id: "otvorit-pauzu", title: "Otvorte Pauza alebo presmerovanie", text: "Použite menu stavu telefónu alebo rovnomenné tlačidlo v Môj telefón. Otvorí sa Pauza a zastupovanie hovorov." },
        { id: "vybrat-dovod", title: "Vyberte Dôvod pauzy", text: "Ak prevádzka používa dôvody, vyberte zodpovedajúci. Pri dôvode môže byť uvedená plánovaná dĺžka v minútach." },
        { id: "vybrat-rezim-pauzy", title: "Vyberte Bežná pauza alebo Zastúpi ma kolega", text: "Pri bežnej pauze sa vaša pozícia preskočí podľa plánu. Pri zastupovaní vyberte Zastupujúci operátor a skontrolujte jeho aktuálny stav." },
        { id: "aktivovat-pauzu", title: "Stlačte Aktivovať pauzu", text: "Počkajte na úspešné nastavenie a skontrolujte zobrazený stav Pauza.", result: "Nové automatické ponuky vám počas pauzy nezvonia. Ak aplikácia oznámi chybu aktivácie, neodchádzajte iba na základe uloženého výberu zastupovania." },
      ], screenshotIds: ["pause"] },
      { id: "bezna-vs-zastup", title: "Čo presne znamená zastupovanie", table: { headers: ["Voľba", "Čo sa deje s pracovnými hovormi"], rows: [["Bežná pauza", "Vám sa hovor neponúkne; plán pokračuje ďalším vhodným členom alebo následným riešením."], ["Zastúpi ma kolega", "Na vašu pozíciu sa použije vybraný kolega, ak je dostupný a môže hovor prijať."]] }, paragraphs: ["Výber kolegu nezapne jeho dostupnosť, neukončí mu iný hovor ani ho nevytrhne z vlastnej pauzy. So zastupujúcim kolegom sa preto najprv dohodnite. Zastupovanie hovorov tiež nemení vlastníka vašich prípadov či úloh; tie odovzdajte osobitne."] },
      { id: "pripomienka-a-navrat", title: "Pripomienka vás sama nevráti do služby", paragraphs: ["Pri dôvode s plánovanou dĺžkou aplikácia upozorní minútu pred plánovaným koncom a po jeho uplynutí. Zobrazený čas je pripomienka, nie automatické zapnutie dostupnosti. Na upozornenia sa nespoliehajte ako na jediný budík, najmä pri zatvorenej aplikácii."], steps: [
        { id: "vratit-sa", title: "Po návrate pripravte pracovisko", text: "Skontrolujte telefón, zvuk a odovzdané položky. Ak ste zmenili zariadenie alebo okno, overte pripojenie." },
        { id: "som-dostupny", title: "Zvoľte Som dostupný", text: "V Môj telefón stlačte Som dostupný; v menu stavu telefónu je voľba Dostupný.", result: "Po úspešnej zmene sa opäť môžete zapojiť do automatických ponúk hovorov." },
      ] },
      { id: "dopisovanie", title: "Dopisovanie je čas na dokončenie zápisu", paragraphs: ["Po ukončení hovoru môže začať dopisovanie. Počas neho vám ďalší automatický hovor ešte nezazvoní, aby ste stihli zaznamenať výsledok. Dĺžku určuje Čas po hovore (s) v Môj telefón.", "Dopisovanie má vlastný odpočet. Po jeho uplynutí prestane blokovať ponuky, ak zostávate dostupný a spĺňate ostatné podmienky. Ak zápis dokončíte skôr, môžete použiť ponúknuté ukončenie dopisovania. Na dlhšiu prestávku zapnite pauzu." ] },
      { id: "nastavit-dovody-pauzy", title: "Pre vedúceho: nastavenie dôvodov pauzy", paragraphs: ["Manažér alebo Admin môže otvoriť Nastavenia → Telefonovanie → Dôvody pauzy. Použite Pridať dôvod, vyplňte Názov, skontrolujte Kód používaný v štatistikách a prípadné Maximum (min). Prázdne maximum znamená bez plánovaného limitu.", "Poradie dôvodov upravte ovládaním presunu, skontrolujte Aktívny a stlačte Uložiť dôvody pauzy. Maximum slúži na plánovanie a pripomienku, neukončuje pauzu automaticky. Dôvod používaný operátorom nemožno odstrániť; pri jeho vyradení z ponuky zvážte vypnutie aktívnosti a prečítajte zobrazené upozornenie."] },
    ], related: ["priprava-na-sluzbu", "moj-telefon", "plany-zvonenia", "ulohy-a-poznamky"], sources: ["src/components/dispatch/PauseRoutingDialog.tsx", "src/components/dispatch/MyPhonePanel.tsx", "src/components/dispatch/HeaderPhoneStatusMenu.tsx", "src/components/dispatch/settings/PauseReasonsEditor.tsx", "src/lib/telephony/pause-ending.ts", "src/server/telephony/routing/eligibility.ts"],
  },
  {
    slug: "pripad", title: "Prípad od prvého kontaktu po uzavretie", description: "Založte kartu zásahu, doplňte klienta a vozidlo a priebežne evidujte postup pomoci.", categoryId: "pripady", audience: "all", minutes: 8,
    keywords: ["prípad", "zásah", "karta", "zákazník", "vozidlo", "incident", "nový", "priorita", "uzavretie"], prerequisites: ["Poznáte aspoň základnú požiadavku klienta.", "Pred vytvorením overte, či už rovnaký zásah nie je založený."],
    sections: [
      { id: "zalozit-pripad", title: "Vytvorte kartu alebo pokračujte v existujúcej", steps: [
        { id: "overit-existujuci-pripad", title: "Vyhľadajte klienta alebo vozidlo", text: "Pozrite aktívne prípady podľa telefónu, mena, čísla prípadu alebo evidenčného čísla vozidla. Pri pokračujúcom zásahu otvorte pôvodnú kartu." },
        { id: "novy-pripad", title: "Zvoľte Nový prípad", text: "Použite tlačidlo Nový prípad alebo vytvorenie z hovoru. Predvyplnené údaje vždy overte s klientom." },
        { id: "zakladne-udaje", title: "Vyplňte typ zákazky a zdroj", text: "Začnite hornou časťou formulára. Typ zákazky ovplyvňuje, ktoré údaje sa ďalej požadujú, napríklad cieľ odťahu alebo údaje náhradného vozidla." },
      ], screenshotIds: ["new-case"] },
      { id: "klient-a-kontakty", title: "Klient a kontakty v poradí volania", paragraphs: ["Zvoľte typ zákazníka a doplňte potrebné údaje klienta alebo firmy. Ak zásah rieši asistencia, odlíšte kontakt na vodiča od kontaktu na asistenčnú službu a jej čísla prípadu.", "Pri kontaktoch vyplňte meno, telefón, rolu a podľa potreby poznámku. Ako Primárny označte hlavný kontakt. Poradie upravte pomocou Vyššie a Nižšie tak, aby kolega vedel, koho kontaktovať najskôr. Telefón potvrďte s klientom; číslo prichádzajúceho hovoru nemusí byť použiteľné na spätné volanie."] },
      { id: "vozidlo-a-incident", title: "Vozidlo, problém a miesto", steps: [
        { id: "opisat-vozidlo", title: "Doplňte identifikáciu vozidla", text: "Zapíšte evidenčné číslo a dostupné údaje vozidla. Pri načítaných údajoch skontrolujte, že patria správnemu vozidlu. Doplňte pojazdnosť a okolnosti potrebné na výber techniky." },
        { id: "opisat-problem", title: "Vyplňte Opis problému / situácie", text: "Popíšte požadovanú pomoc, typ incidentu a relevantné poškodenie či komplikácie. Zápis má umožniť ďalšiemu dispečerovi pokračovať bez opätovného zisťovania základov." },
        { id: "urcit-miesto", title: "Potvrďte Miesto incidentu a prípadný Cieľ odťahu", text: "Vyberte použiteľné miesto na mape alebo z vyhľadávania. Na ceste doplňte smer jazdy, úsek a prístup k vozidlu. Pri potrebnom odťahu doplňte aj cieľ." },
      ] },
      { id: "ulozit-novu-kartu", title: "Novú kartu treba výslovne uložiť", steps: [
        { id: "skontrolovat-policka", title: "Skontrolujte zvýraznené polia", text: "Doplňte chýbajúce informácie a opravte neplatné hodnoty. Ak časť informácií ešte nepoznáte, použite možnosť rozpracovanej karty." },
        { id: "ulozit-kartu", title: "Stlačte Uložiť kartu alebo Uložiť rozpracované", text: "Počkajte na potvrdenie vytvorenia.", result: "Prípad má svoje číslo a je dostupný v zozname. Rozpracovanú kartu treba neskôr doplniť; jej uloženie nepotvrdzuje úplnosť údajov." },
      ], note: { tone: "important", title: "Nový a existujúci prípad sa ukladajú odlišne", text: "Nový prípad vytvoríte tlačidlom. Úpravy existujúcej karty sa ukladajú automaticky; kontrolujte hlášku Uložené automaticky. Úlohy, poznámky a nahratie prílohy majú vlastné potvrdenie." } },
      { id: "viest-zasah", title: "Počas riešenia udržujte kartu aktuálnu", paragraphs: ["Skontrolujte zodpovedného dispečera, prioritu a stav prípadu. Podľa potreby priraďte vhodnú techniku a doplňte služby. Zmena zodpovedného dispečera nenahrádza odovzdanie otvorených úloh a čakajúcich hovorov.", "Zapisujte dohodnuté kroky a zmeny, pripojte hovor, posielané SMS a potrebné prílohy. Dôležité termíny vytvárajte ako úlohy s konkrétnou zodpovednou osobou. Po úprave počkajte na potvrdenie automatického uloženia."], screenshotIds: ["case-detail"] },
      { id: "uzavriet-pripad", title: "Ukončenie prípadu", steps: [
        { id: "overit-dokoncenie", title: "Overte dokončenie pomoci", text: "Skontrolujte výsledok zásahu, otvorené úlohy, potrebné doklady a stav platby. Doplňte Typ ukončenia a Poznámka k ukončeniu zásahu podľa použitého postupu." },
        { id: "zmenit-stav", title: "Nastavte zodpovedajúci stav prípadu", text: "Vyberte stav, ktorý zodpovedá skutočnému výsledku, a počkajte na uloženie. Neúspešné volanie alebo odovzdanie kolegovi samo osebe neznamená ukončený zásah.", result: "Uložený výsledok je dohľadateľný v karte a v histórii prípadov. Podklady na fakturáciu riešte ako ďalší samostatný krok." },
      ] },
    ], related: ["mapa-a-sms", "ulohy-a-poznamky", "historia-a-dokoncenie"], sources: ["src/components/dispatch/NewCaseDrawer.tsx", "src/components/dispatch/CaseDetail.tsx", "src/components/dispatch/CaseEditorHeader.tsx", "src/components/dispatch/CaseList.tsx"],
  },
  {
    slug: "mapa-a-sms", title: "Mapa, poloha a komunikácia", description: "Vyžiadajte polohu, potvrďte miesto zásahu a odošlite správu klientovi.", categoryId: "pripady", audience: "all", minutes: 6,
    keywords: ["mapa", "GPS", "poloha", "SMS", "trasa", "ETA", "miesto", "navigácia", "správa"], prerequisites: ["Máte otvorený správny prípad.", "Na vyžiadanie polohy potrebujete telefón klienta a dostupné odosielanie SMS."],
    sections: [
      { id: "vyber-miesta", title: "Miesto musí byť použiteľné na mape", paragraphs: ["V karte prípadu vyhľadajte adresu a vyberte konkrétny výsledok alebo použite výber na mape. Overte bod s klientom. Samotný text názvu obce nemusí určiť presné miesto zásahu.", "Pri diaľnici a podobných miestach doplňte smer, úsek a prístup. Cieľ odťahu evidujte osobitne od miesta incidentu. Keď chýba použiteľné miesto, trasa, navigácia a odhad príchodu sa nemusia sprístupniť."] },
      { id: "vyziadat-polohu", title: "Ako vyžiadať polohu od klienta", steps: [
        { id: "overit-telefon-gps", title: "Overte telefón klienta", text: "Skontrolujte, že ide o číslo človeka pri vozidle, ktorý môže otvoriť SMS a povoliť zdieľanie polohy." },
        { id: "odoslat-ziadost-gps", title: "Použite žiadosť o polohu", text: "V komunikácii prípadu spustite vyžiadanie polohy. Klientovi príde SMS s odkazom; vysvetlite mu, aby odkaz otvoril a potvrdil odoslanie polohy." },
        { id: "skontrolovat-prijatu-gps", title: "Pozrite GPS od klienta", text: "Po doručení skontrolujte čas a dostupný údaj o presnosti. Porovnajte bod s opisom miesta.", result: "Poloha sa najprv zobrazí ako doplnková informácia. Miesto incidentu, trasa a odhad príchodu sa neprepíšu automaticky." },
      ], screenshotIds: ["sms"] },
      { id: "pouzit-polohu", title: "Potvrďte, či má GPS nahradiť miesto incidentu", paragraphs: ["Ak prijatá poloha zodpovedá skutočnému miestu zásahu, použite pri nej ovládanie na použitie polohy. Predtým nechajte uložiť rozpracovanú kartu. Po potvrdení skontrolujte nové miesto a nadväzujúcu trasu.", "Otvoriť GPS vám ukáže súradnice v mape, ale samotné otvorenie ešte nemení miesto incidentu. Ak klient polohu odmietne alebo pošle nepresný bod, dohodnite miesto hlasom a zadajte ho ručne."] },
      { id: "odoslat-sms", title: "Vlastná SMS klientovi", steps: [
        { id: "otvorit-sms", title: "Otvorte odoslanie SMS", text: "V prípade použite akciu pre SMS. Skontrolujte príjemcu; vlastnú SMS možno podľa formulára poslať aj na ručne zadané číslo." },
        { id: "napisat-spravu", title: "Napíšte a skontrolujte text", text: "Uveďte jasný ďalší krok a podľa potreby identifikáciu prípadu. Pred odoslaním overte číslo aj obsah, najmä pri preberaní textu zo staršej komunikácie." },
        { id: "odoslat-spravu", title: "Potvrďte odoslanie", text: "Sledujte výsledok a históriu správ. Pri chybe najprv zistite stav pôvodnej správy, aby ste klientovi neposlali zbytočné duplicity.", result: "Správa je evidovaná s dostupným stavom odoslania. Odoslanie nie je potvrdenie, že ju klient prečítal." },
      ] },
      { id: "trasa-a-odhad", title: "Trasa a odhad príchodu", paragraphs: ["Po zadaní použiteľného miesta a prípadného cieľa skontrolujte trasu. Odhad príchodu vychádza z dostupných údajov; pri jeho oznámení klientovi zohľadnite aktuálnosť polohy techniky a dohodu s vodičom.", "Pri zmene miesta, vozidla alebo cieľa overte, či sa aktualizovali aj súvisiace údaje. Históriu hovorov, SMS a poznámok používajte spoločne, aby mal ďalší dispečer úplný kontext."] },
    ], related: ["pripad", "flotila-a-adresar", "historia-a-dokoncenie"], sources: ["src/components/dispatch/CaseDetail.tsx", "src/components/dispatch/LocationPicker.tsx", "src/components/dispatch/SmsComposerDialog.tsx", "src/components/dispatch/SmsHistory.tsx"],
  },
  {
    slug: "ulohy-a-poznamky", title: "Úlohy, poznámky a odovzdanie práce", description: "Dajte ďalšiemu kroku termín a vlastníka; pracovný kontext odovzdajte na správnom mieste.", categoryId: "pripady", audience: "all", minutes: 7,
    keywords: ["úloha", "poznámka", "odovzdanie", "termín", "pripomenutie", "zdieľanie", "upozornenie", "chat"], prerequisites: ["Ste prihlásený; pre úlohu k prípadu poznáte správne číslo prípadu."],
    sections: [
      { id: "vybrat-zaznam", title: "Úloha, poznámka prípadu a osobná poznámka", table: { headers: ["Potrebujete", "Použite"], rows: [["Aby niekto niečo urobil do určitého času", "Úlohu so zodpovednou osobou, termínom a prípadným pripomenutím."], ["Zapísať dohodu alebo priebeh zásahu", "Poznámky a aktivitu v karte prípadu."], ["Vlastný pracovný zápis alebo podklad pre vybraných kolegov", "Poznámky; nová poznámka je súkromná, kým ju nezdieľate."]] } },
      { id: "vytvorit-ulohu", title: "Ako vytvoriť úlohu", steps: [
        { id: "nova-uloha", title: "Otvorte Úlohy → Nová úloha", text: "Úlohu môžete pridať aj priamo z prípadu. Napíšte konkrétny Názov úlohy, napríklad „Overiť čas príchodu techniky“; tento názov je iba príklad." },
        { id: "urcit-zodpovednost", title: "Vyberte Zodpovedná osoba a termín", text: "Nastavte Termín úlohy, Priorita úlohy a podľa potreby Pripomenúť o. Bez samostatného času pripomenutia sa použije termín úlohy." },
        { id: "pripojit-pripady", title: "Vyberte Pripojené prípady", text: "Úloha môže patriť k jednému alebo viacerým prípadom. Bez výberu vznikne samostatná úloha. Podľa potreby zapnite Pripomienka aj emailom." },
        { id: "vytvorit-ulohu-potvrdit", title: "Stlačte Vytvoriť úlohu", text: "Pri úprave existujúcej použite Uložiť úlohu. Počkajte na potvrdenie; text označený Rozpracované ešte nemusí byť uložený.", result: "Úlohu nájdete v pracovnom zozname aj pri pripojených prípadoch." },
      ], screenshotIds: ["tasks"] },
      { id: "pracovat-s-ulohou", title: "Priebeh a dokončenie úlohy", paragraphs: ["Filtre Moje, Dnes a Po termíne pomôžu určiť, čomu sa venovať. V detaile úlohy používajte správy na priebežnú dohodu. Zmenu zodpovednosti a termínu uložte; dokončenú úlohu označte ako Vybavená alebo použite Vybaviť v prípade.", "Úloha pripojená k viacerým prípadom je stále jedna spoločná úloha. Odpojiť tento prípad odstráni iba väzbu. Vymazať celú úlohu odstráni úlohu zo všetkých pripojených prípadov aj so správami, preto si prečítajte potvrdenie."] },
      { id: "osobne-poznamky", title: "Vlastné a zdieľané poznámky", steps: [
        { id: "nova-poznamka", title: "Otvorte Poznámky → Nová", text: "Vyplňte Názov a Text poznámky. Bez vybraných čitateľov zostáva súkromná." },
        { id: "zdielat-poznamku", title: "Prípadne otvorte Zdieľať s kolegami", text: "Vyberte konkrétnych kolegov. Zdieľanú poznámku môžu čítať; neupravujú ju namiesto vás." },
        { id: "ulozit-poznamku", title: "Stlačte Uložiť", text: "Uložte text aj zmeny zdieľania.", result: "Vybraní kolegovia ju uvidia medzi zdieľanými poznámkami. Vymazanie poznámky odstráni prístup aj jej čitateľom." },
      ], screenshotIds: ["notes"] },
      { id: "upozornenia", title: "Upozornenie je pripomenutie práce", paragraphs: ["Upozornenia otvárajte v hlavičke aplikácie. Pri úlohe si skontrolujte aktuálny termín, stav a zodpovednú osobu. Prečítanie alebo odloženie upozornenia nenahrádza vykonanie úlohy a označenie jej výsledku.", "E-mailové a systémové upozornenia závisia aj od nastavenia doručovania a zariadenia. Pri práci preto pravidelne kontrolujte aj zoznam vlastných a oneskorených úloh."], screenshotIds: ["notifications"] },
      { id: "odovzdanie", title: "Odovzdajte ďalší krok, nielen všeobecnú poznámku", bullets: ["Uveďte číslo prípadu a čo je už vybavené.", "Pomenujte, na čo sa čaká, koho treba kontaktovať a dokedy.", "Nastavte zodpovednú osobu pri úlohách a dohodnite prevzatie.", "Upozornite na odložený hovor alebo prevzatú spätnú požiadavku.", "Počkajte na uloženie všetkých rozpracovaných údajov." ] },
    ], related: ["pripad", "pauza-a-zastupovanie", "dochadzka"], sources: ["src/components/dispatch/TaskWorkspacePanel.tsx", "src/components/dispatch/TaskChatPanel.tsx", "src/components/dispatch/NotebookPanel.tsx", "src/components/dispatch/CaseDetail.tsx", "src/components/dispatch/HeaderNotificationMenu.tsx"],
  },
  {
    slug: "historia-a-dokoncenie", title: "Vyhľadávanie a administratívne dokončenie", description: "Nájdite starší prípad, pripojte doklady, pripravte PDF a riešte neuložené zmeny.", categoryId: "pripady", audience: "all", minutes: 5,
    keywords: ["história", "filtre", "hľadanie", "PDF", "faktúra", "príloha", "automatické uloženie", "konflikt"], prerequisites: ["Ste prihlásený a poznáte aspoň jeden údaj hľadaného prípadu."],
    sections: [
      { id: "najst-pripad", title: "Ako nájsť prípad", steps: [
        { id: "otvorit-pripady", title: "Otvorte Prípady", text: "Podľa situácie vyberte Aktívne alebo História. Ukončený prípad nemusí byť v aktívnom zozname." },
        { id: "pouzit-hladanie", title: "Vyhľadajte známy údaj", text: "Použite číslo prípadu, klienta, telefón alebo vozidlo podľa ponuky vyhľadávania. Skontrolujte zvolené filtre aj poradie." },
        { id: "overit-zaznam", title: "Otvorte a porovnajte kartu", text: "Overte dátum, kontakt a vozidlo, aby ste nepokračovali v inom zásahu toho istého klienta.", result: "Pracujete so správnym prípadom a jeho históriou komunikácie." },
      ], screenshotIds: ["cases"] },
      { id: "prilohy", title: "Priloženie dokumentov", steps: [
        { id: "pridat-subor", title: "V časti príloh zvoľte Pridať súbor", text: "Vyberte príslušné fotografie alebo doklady a skontrolujte zoznam vybraných súborov. Omylom vybraný súbor odoberte pred nahratím." },
        { id: "nahrat-subor", title: "Stlačte Nahrať", text: "Počkajte na výsledok. Výber súboru na počítači ešte neznamená, že bol nahratý k prípadu.", result: "Súbor je uvedený medzi prílohami a možno ho otvoriť. Pri novej karte sledujte aj výsledok vytvorenia prípadu a jeho príloh." },
      ], paragraphs: ["Formulár uvádza povolené typy a veľkosť. Aktuálne povoľuje JPG, PNG, PDF a Word do 10 MB. Pri neúspechu najprv skontrolujte formát, veľkosť a pripojenie."] },
      { id: "pdf-a-fakturacia", title: "PDF prípadu a príprava fakturácie", paragraphs: ["V detaile prípadu použite PDF na stiahnutie prehľadu uložených údajov. Pred exportom nechajte uložiť rozpracované zmeny a skontrolujte obsah hotového dokumentu.", "Akcia Faktúra spúšťa prípravu fakturácie. Nie je sama osebe potvrdením vystavenia alebo odoslania faktúry. Skontrolujte potvrdenie aplikácie a následný postup používaný vo vašej organizácii. Stav platby v karte udržujte podľa skutočného výsledku."] },
      { id: "ulozenie", title: "Ako spoznáte uložené zmeny", table: { headers: ["Obsah", "Ako sa ukladá"], rows: [["Nová karta", "Uložiť kartu alebo Uložiť rozpracované."], ["Úprava existujúcej karty", "Automaticky; sledujte Ukladám automaticky a následné potvrdenie."], ["Úloha", "Vytvoriť úlohu alebo Uložiť úlohu."], ["Osobná poznámka", "Uložiť."], ["Príloha", "Nahrať; pri novej karte aj dokončenie vytvorenia prípadu."]] }, paragraphs: ["Pri výpadku pripojenia alebo chybe nechajte formulár otvorený a riaďte sa hláškou. Zobrazené údaje môžu byť stále iba vašou rozpracovanou verziou. Pri odchode použite ponúknuté uloženie alebo počkajte na automatické uloženie."] },
      { id: "konflikt-zmien", title: "Keď údaje medzitým zmenil kolega", paragraphs: ["Upozornenie na novšiu verziu znamená, že rovnaký záznam zmenil iný používateľ alebo iné okno. Najprv si pozrite hlášku a dohodnite sa s kolegom, čo sa má zachovať.", "V prípade je dostupné Načítať aktuálny stav prípadu. Pri úlohách a poznámkach používajte ich vlastné načítanie aktuálnej verzie. Pred potvrdením si prečítajte, či sa rozpracovaný text zachová alebo nahradí. Dôležité neuložené údaje si dočasne zachovajte a potrebné zmeny potom znova uložte." ] },
    ], related: ["pripad", "ulohy-a-poznamky", "riesenie-problemov"], sources: ["src/components/dispatch/CaseList.tsx", "src/components/dispatch/CaseDetail.tsx", "src/components/dispatch/NewCaseDrawer.tsx", "src/components/dispatch/TaskWorkspacePanel.tsx", "src/components/dispatch/NotebookPanel.tsx", "src/lib/case-attachments.ts"],
  },
  {
    slug: "cesta-hovoru", title: "Ako sa hovor dostane k operátorovi", description: "Jednoduché vysvetlenie vzťahu medzi číslom, plánom, skupinou a dostupnosťou.", categoryId: "nastavenia", audience: "all", minutes: 6,
    keywords: ["smerovanie", "cesta hovoru", "ústredňa", "skupina", "plán", "krok", "linka", "fallback", "IVR"], prerequisites: ["Na pochopenie nepotrebujete meniť nastavenia.", "Na uloženie skupín, plánov a smerovania potrebujete rolu Manažér alebo Admin."],
    sections: [
      { id: "schema", title: "Základná cesta prichádzajúceho hovoru", flow: ["Klient zavolá na telefónne číslo", "Uplatní sa smerovanie linky a otváracie hodiny", "Prípadné IVR vyberie ďalšiu cestu", "Plán spustí prvý krok so skupinou", "Hovor sa ponúkne vhodnému operátorovi", "Prijatie, ďalší krok alebo následné riešenie"], paragraphs: ["Presná cesta závisí od uloženej linky. Nie každá linka používa IVR alebo otváracie hodiny. Linka môže navyše smerovať cez Návrat na hlavnú linku; vtedy treba skontrolovať aj zvolenú hlavnú linku."] },
      { id: "co-urcuje-ktora-cast", title: "Každá časť má inú úlohu", table: { headers: ["Pojem", "Jednoduché vysvetlenie"], rows: [["Číslo / linka", "Vstup, na ktorý klient volá. Vyberá plán, prípadné IVR a pracovný čas."], ["Skupina", "Zoznam operátorov alebo externých telefónnych cieľov. Určuje komu."], ["Krok", "Jedna skupina v konkrétnom poradí s časom a spôsobom zvonenia."], ["Plán", "Poradie krokov a čo sa stane, keď nikto nezdvihne. Určuje ako pokračovať."], ["Dostupnosť", "Momentálny stav človeka a jeho telefónu; určuje, či môže dostať ponuku."], ["IVR", "Hlasové menu, v ktorom klient stláča klávesy na telefóne."]] } },
      { id: "spolocny-priklad", title: "Jeden príklad pre celý návod", paragraphs: ["Tréningový príklad: linka má prvý krok so skupinou „Denná služba“, v ktorej sú Jana a Peter. Zvoní im všetkým naraz 20 sekúnd. Ak nikto nezdvihne, druhý krok skúsi skupinu „Záloha“ s Martinom na 15 sekúnd. Po vyčerpaní krokov klient čaká v čakárni.", "Ak Jana prijme, ďalší krok sa už nespustí. Ak je Jana na pauze, jej automatická ponuka sa nespustí alebo ju podľa zastupovania dostane vhodný kolega. Ak nikto z prvého kroku nemôže prijať, plán môže pokračovať bez čakania na celý ukážkový čas."], note: { tone: "info", title: "Ide o príklad, nie o vaše uložené nastavenie", text: "Mená, názvy skupín a časy v návode a na obrázkoch sú tréningové údaje. Skutočné hodnoty si pozrite v Nastavenia → Telefonovanie pre konkrétnu linku." } },
      { id: "nastavenie-vs-dostupnost", title: "Členstvo v skupine ešte neznamená zvonenie", paragraphs: ["Operátor môže byť členom skupiny a napriek tomu hovor nedostane: je na pauze, telefonuje, dopisuje po hovore, nemá pripravené zariadenie alebo už má inú ponuku. Pri súčasnom zvonení sa môže uplatniť aj limit počtu naraz volaných členov.", "Plán opisuje zamýšľané poradie. Aktuálna dostupnosť a spojenie určujú, čo možno práve teraz vykonať. Pri otázke „Prečo mi nezvoní?“ preto skontrolujte obidve veci."] },
      { id: "co-kontrolovat-po-zmene", title: "Nastavenie treba uložiť aj priradiť", paragraphs: ["Vytvorenie skupiny nepridá skupinu automaticky do plánu. Vytvorenie plánu nepriradí plán automaticky k číslu. Po každej zmene overte celý sled: aktívni členovia → skupina → kroky plánu → konkrétna linka alebo voľba IVR.", "Zmeny skupín a plánov sa použijú pri nových hovoroch. Rozbehnutý hovor môže pokračovať podľa plánu, ktorý dostal pri začiatku. Výsledok nastavenia preto overujte novým dohodnutým skúšobným hovorom."] },
    ], related: ["skupiny-zvonenia", "plany-zvonenia", "cisla-hodiny-a-ivr", "pauza-a-zastupovanie"], sources: ["src/components/dispatch/settings/ring-groups-model.ts", "src/components/dispatch/settings/ring-plan-model.ts", "src/server/telephony/routing/ring-plan.ts", "src/server/telephony/routing/eligibility.ts", "src/components/dispatch/settings/NumbersPanel.tsx"],
  },
  {
    slug: "moj-telefon", title: "Môj telefón a operátori", description: "Vyberte spôsob prijímania, odchádzajúce číslo, zvuk a čas na dokončenie hovoru.", categoryId: "nastavenia", audience: "all", minutes: 6,
    keywords: ["môj telefón", "operátori", "osobný mobil", "odchádzajúca linka", "zvukový výstup", "SIP", "iné okno"], prerequisites: ["V Nastavenia → Telefonovanie máte otvorené Môj telefón.", "Nastavenia iných operátorov upravuje Manažér alebo Admin."],
    sections: [
      { id: "rezimy-prijimania", title: "Tri rôzne spôsoby používania telefónu", table: { headers: ["Možnosť", "Ako ju chápať"], rows: [["Telefón v aplikácii", "Hovor vybavujete vo webovej aplikácii so zvukom a mikrofónom zariadenia."], ["Prijímam na osobnom mobile", "Pracovná ponuka smeruje na uložené osobné telefónne číslo. Hovor prijmete v bežnom telefóne."], ["Samostatná SIP aplikácia", "Osobitne pripravené telefónne zariadenie alebo aplikácia. Nie je to automaticky webová aplikácia otvorená na mobile."]] }, paragraphs: ["Podporu konkrétneho mobilu a prípadného samostatného telefónneho zariadenia si potvrďte so správcom. Režim prijímania si nezamieňajte s pauzou ani s nastavením odchádzajúcej linky."], screenshotIds: ["phone-settings"] },
      { id: "ulozit-osobne-nastavenia", title: "Upravte Moje nastavenia hovorov", steps: [
        { id: "nastavit-odchadzajucu-linku", title: "Vyberte Odchádzajúca linka", text: "Zvoľte pracovné číslo, ktoré má vidieť volaný. Predvolená systémová voľba používa číslo určené organizáciou." },
        { id: "nastavit-dopisovanie", title: "Nastavte Čas po hovore (s)", text: "Zadajte potrebný čas na dokončenie zápisu. Je to interval bez ďalšej automatickej ponuky po zložení; na prestávku používajte pauzu." },
        { id: "nastavit-prijimanie", title: "Vyberte Prijímanie hovorov", text: "Pri osobnom mobile doplňte a overte Môj mobil. Pri práci v aplikácii skontrolujte jej telefón a mikrofón." },
        { id: "ulozit-moj-telefon", title: "Uložte nastavenia", text: "Stlačte Uložiť moje nastavenia a skontrolujte potvrdenie.", result: "Nastavenia sú uložené. Dostupnosť sa tým automaticky nezapne; samostatne použite Som dostupný." },
      ] },
      { id: "zvuk-a-skusobny-hovor", title: "Kam ide zvuk hovoru", paragraphs: ["V časti Zvukový výstup vyberte Kam ide zvuk hovoru, ak to prehliadač podporuje. Voľba platí pre daný počítač a prehliadač. Ak zariadenie chýba, skontrolujte jeho pripojenie a systémové nastavenia zvuku.", "Hlasitosť zvonenia a počuteľnosť overte prakticky na svojom zariadení. Samotná hodnota uložená pri operátorovi nie je potvrdením hlasitosti zvonenia prehliadača. Kontrola mikrofónu nevytáča číslo; Skúšobný hovor je skutočný a spoplatnený hovor na zvolený cieľ."] },
      { id: "telefon-v-inom-okne", title: "Telefón je v inom okne", paragraphs: ["Pri viacerých otvorených oknách môže telefón obsluhovať iné okno. V okne, v ktorom chcete pracovať, otvorte stav telefónu a použite Prevziať telefón do tohto okna. Ak telefón ešte nie je pripojený, môže sa ponúkať Pripojiť telefón v tomto prehliadači.", "Prevzatie robte vedome medzi pracovnými oknami a mimo aktívneho hovoru. Po zmene overte pripojenie aj dostupnosť. Samotné otvorenie návodu nevyžaduje prevzatie telefónu."] },
      { id: "nastavenia-kolegov", title: "Nastavenia operátorov pre vedúceho", paragraphs: ["Manažér a Admin nájdu v Nastavenia → Telefonovanie → Operátori nastavenia kolegov a ich telefónov. Najprv vyberte správneho človeka; dostupnosť, osobný mobil a členstvo v skupinách posudzujte spoločne.", "Pri zmene prijímania sa s kolegom dohodnite, na ktorom zariadení bude pracovať. Po uložení overte jeho vlastný pohľad Môj telefón a dohodnutý skúšobný hovor. Uložená konfigurácia nie je dôkazom, že je zariadenie práve pripojené."] },
    ], related: ["priprava-na-sluzbu", "pauza-a-zastupovanie", "skupiny-zvonenia"], sources: ["src/components/dispatch/MyPhonePanel.tsx", "src/components/dispatch/HeaderPhoneStatusMenu.tsx", "src/components/dispatch/settings/OperatorsTelephonyPanel.tsx", "src/components/dispatch/settings/operators-model.ts"],
  },
  {
    slug: "skupiny-zvonenia", title: "Skupiny zvonenia", description: "Určte členov, ich poradie a rozdiel medzi operátorom a externou zálohou.", categoryId: "nastavenia", audience: "manager", minutes: 7,
    keywords: ["skupina", "člen", "operátor", "externé číslo", "záloha", "poradie", "vlastník", "čas člena"], prerequisites: ["Rola Manažér alebo Admin na ukladanie zmien.", "Zoznam ľudí a povolených telefónnych cieľov, ktoré sa majú zapojiť."],
    sections: [
      { id: "ucel-skupiny", title: "Skupina určuje komu sa ponúkne hovor", paragraphs: ["Skupina je zoznam členov, napríklad dennej služby alebo prevádzkovej zálohy. Neurčuje sama, na ktorom čísle a v ktorom kroku sa použije. To nastavíte v pláne a pri linke.", "Jedna skupina môže byť v niekoľkých plánoch. Zmena jej členov sa preto môže dotknúť viacerých liniek. Pred úpravou si prečítajte zobrazené použitie skupiny a účinné časy v uložených plánoch."], screenshotIds: ["groups"] },
      { id: "vytvorit-skupinu", title: "Vytvorenie alebo úprava skupiny", steps: [
        { id: "otvorit-skupiny", title: "Otvorte Nastavenia → Telefonovanie → Skupiny", text: "Vyberte existujúcu skupinu alebo stlačte Pridať skupinu." },
        { id: "pomenovat-skupinu", title: "Vyplňte Názov skupiny", text: "Použite názov zrozumiteľný pre kolegov, napríklad „Denná služba“. Do Poznámka môžete doplniť jej účel; názov je tréningový príklad." },
        { id: "pridat-clenov", title: "Pridajte Operátor alebo Externé číslo", text: "Pri operátorovi vyberte človeka zo zoznamu. Pri externom cieli doplňte celé číslo a skontrolujte, či ide o osobný telefón alebo samostatnú prevádzkovú zálohu." },
        { id: "poradie-clenov", title: "Usporiadajte členov", text: "Použite ovládanie presunu pri členovi. Prvý člen je prvý kandidát pri postupnom zvonení; pri súčasnom režime môže poradie ovplyvniť aj výber do limitu organizácie." },
        { id: "ulozit-skupiny", title: "Skontrolujte aktívnosť a Uložiť skupiny", text: "Opravte zvýraznené chyby a počkajte na potvrdenie.", result: "Uloženú skupinu môžete vybrať do kroku plánu. Bez takéhoto priradenia nová skupina ešte sama neprijíma hovory." },
      ] },
      { id: "operator-vs-externy-ciel", title: "Operátor a externé číslo sa správajú odlišne", paragraphs: ["Operátor sa posudzuje podľa vlastnej dostupnosti a pripraveného spôsobu prijímania. Keď je na pauze alebo má iný hovor, jeho meno v skupine samo osebe nezaručuje ponuku.", "Pri Externé číslo skontrolujte Vlastník externého čísla. Osobné číslo naviazané na operátora rešpektuje jeho pauzu. Samostatná prevádzková záloha je osobitný telefónny cieľ. Osobný mobil nezaraďujte ako nezávislú zálohu len preto, aby obišiel pauzu majiteľa.", "Externé číslo musí byť povoleným cieľom organizácie. Ak formulár jeho uloženie odmietne, nechajte správcu preveriť cieľ; nenahrádzajte ho odhadnutým číslom."] },
      { id: "cas-clena", title: "Zvonenie (s) pri členovi", table: { headers: ["Nastavenie kroku", "Význam času člena"], rows: [["Postupne", "Vlastný čas člena určuje, ako dlho sa mu ponúka hovor. Prázdne pole preberá čas kroku."], ["Všetkým naraz", "Použije sa spoločný čas kroku. Vlastné časy členov sa v tomto kroku nepoužijú."]] }, paragraphs: ["Tréningový príklad: traja členovia bez vlastného času a krok Postupne s časom 20 sekúnd môžu spolu zvoniť až 60 sekúnd. Ak prvý prijme skôr alebo niektorý nie je dostupný, skutočný čas bude kratší. Účinné časy si prečítajte priamo pri použití skupiny v pláne."] },
      { id: "vypnutie-a-odstranenie", title: "Vypnutie a odstránenie skupiny", paragraphs: ["Vypnutá skupina sa pri zostavení nového hovoru do plánu nezapojí. Ak tým z plánu vypadnú všetky použiteľné kroky, bežné zvonenie sa nespustí; aplikácia na následok upozorňuje. Skupinu nevypínajte bez kontroly jej použitia.", "Skupinu používanú plánom nemožno jednoducho odstrániť. Najprv upravte kroky všetkých príslušných plánov a uložte ich. Po zmene členov alebo aktívnosti overte novým skúšobným hovorom, komu sa ponuka skutočne zobrazí."] },
    ], related: ["cesta-hovoru", "plany-zvonenia", "pauza-a-zastupovanie"], sources: ["src/components/dispatch/settings/RingGroupsEditor.tsx", "src/components/dispatch/settings/ring-groups-model.ts", "src/server/telephony/routing/ring-plan.ts", "src/server/telephony/routing/eligibility.ts"],
  },
  {
    slug: "plany-zvonenia", title: "Plány a kroky zvonenia", description: "Poskladajte poradie skupín, správne prečítajte časy a určte, čo nasleduje po neprijatí.", categoryId: "nastavenia", audience: "manager", minutes: 9,
    keywords: ["plán zvonenia", "krok", "postupne", "všetkým naraz", "čas", "timeout", "poradie", "fallback", "nikto nezdvihne"], prerequisites: ["Rola Manažér alebo Admin na ukladanie zmien.", "Aspoň jedna uložená skupina s vhodnými členmi.", "Viete, ktorá linka alebo voľba IVR má plán používať."],
    sections: [
      { id: "co-je-plan", title: "Plán určuje poradie aj posledné riešenie", paragraphs: ["Plán postupne prechádza kroky. Každý krok vyberá jednu skupinu, čas a spôsob zvonenia. Keď operátor hovor prijme, ďalšie kroky sa nespúšťajú. Ak nikto nezdvihne alebo nie je vhodný člen, pokračuje ďalší krok a nakoniec nastavené riešenie.", "Zmena plánu sa môže dotknúť viacerých liniek aj volieb IVR. Zobrazený zoznam použití si prečítajte pred uložením."], screenshotIds: ["ring-plans"] },
      { id: "zostavit-plan", title: "Ako zostaviť plán", steps: [
        { id: "pridat-plan", title: "Otvorte Plány zvonenia a Pridať plán", text: "Cesta je Nastavenia → Telefonovanie → Plány zvonenia. Vyplňte Názov plánu a skontrolujte jeho aktívnosť." },
        { id: "pridat-prvy-krok", title: "Stlačte Pridať krok", text: "Vyberte Skupina, zadajte Čas (s) a zvoľte Ako zvoní. Začnite skupinou, ktorá má obsluhovať väčšinu hovorov." },
        { id: "pridat-dalsi-krok", title: "Pridajte ďalší krok podľa potreby", text: "Vyberte záložnú skupinu a jej čas. Ovládaním presunu upravte poradie krokov tak, aby zodpovedalo požadovanému postupu." },
        { id: "nastavit-koniec-planu", title: "Vyberte Keď nikto nezdvihne", text: "Určte čakáreň, ponuku spätného volania, presmerovanie na číslo alebo záverečnú hlášku podľa prevádzkového postupu." },
        { id: "ulozit-plan", title: "Prečítajte súhrn a Uložiť plány", text: "Skontrolujte účinné časy, upozornenia a všetky použité skupiny. Opravte chyby a uložte.", result: "Plán je uložený. Nový plán ešte treba priradiť k linke alebo voľbe IVR." },
      ] },
      { id: "vsetkym-naraz", title: "Všetkým naraz: jeden spoločný čas", paragraphs: ["Všetci vybraní vhodní členovia v tomto kroku dostanú ponuku súčasne. Čas kroku je spoločný; vlastné časy pri členoch sa nepoužijú. Prijatím jedného člena sa ostatné ponuky ukončia.", "Tréningový príklad: Jana, Peter a Martin, Všetkým naraz, Čas 20 s. Ak nikto neprijme a všetci môžu dostať ponuku, ide približne o jednu spoločnú 20-sekundovú fázu, nie tri fázy za sebou."], flow: ["Začiatok kroku", "Jana + Peter + Martin dostanú ponuku naraz", "Najviac spoločný čas 20 s v tomto príklade", "Prijatie alebo ďalší krok"], note: { tone: "important", title: "Limit súčasného zvonenia", text: "Organizácia môže obmedziť počet naraz volaných členov. Členovia nad tento limit sa v danom súčasnom kroku nemusia vytočiť vôbec. Sledujte upozornenie a nevysvetľujte názov Všetkým naraz ako bezpodmienečný sľub pre celú veľkú skupinu." } },
      { id: "postupne", title: "Postupne: čas sa môže sčítať za členov", paragraphs: ["Pri Postupne sa ponuky dávajú členom podľa poradia. Člen s vlastným časom Zvonenie (s) používa tento čas; člen s prázdnym poľom preberá Čas (s) z kroku. Čas kroku preto nie je univerzálny spoločný limit celej skupiny.", "Tréningový príklad: traja dostupní členovia bez vlastného času a Čas 20 s môžu zvoniť po sebe 20 + 20 + 20, teda až 60 sekúnd. Ak má Peter vlastný čas 10 s, rovnaký príklad dáva 20 + 10 + 20, teda až 50 sekúnd. Skutočný priebeh skracuje prijatie a nedostupnosť členov."], flow: ["Jana: najviac 20 s", "Ak neprijme, Peter: najviac 20 s", "Ak neprijme, Martin: najviac 20 s", "Až 60 s zvonenia v tréningovom príklade"], note: { tone: "info", title: "Čítajte Účinný čas kroku", text: "Aplikácia pri kroku vysvetľuje časy jednotlivých členov a ich zdroj. Celková skúsenosť volajúceho môže zahŕňať navyše úvodné hlášky, IVR a následné čakanie." } },
      { id: "ked-nikto-nezdvihne", title: "Posledné riešenie po vyčerpaní krokov", table: { headers: ["Možnosť", "Výsledok pre klienta"], rows: [["Čakáreň", "Zostáva na linke a čaká na ďalšiu príležitosť spojenia; platia pravidlá a limit čakania."], ["Ponuka spätného volania", "Dostane možnosť požiadať o zavolanie. Potvrdená požiadavka je následná práca dispečera."], ["Presmerovanie na externé číslo", "Systém skúsi povolený cieľ uvedený v Číslo presmerovania."], ["Záverečná hláška a ukončenie", "Prehrá sa určené oznámenie a hovor sa ukončí."]] }, paragraphs: ["Toto pole sa používa po vyčerpaní vykonaného plánu. Ak je plán vypnutý alebo z neho nezostane žiadny spustiteľný krok, plán sa vôbec nespustí a systém môže prejsť priamo na ponuku spätného volania. Nenahrádzajte preto odstavenie prevádzky náhodným vypínaním skupín; čítajte konkrétne upozornenie v editore."] },
      { id: "priradenie-a-overenie", title: "Priraďte plán a overte celý postup", steps: [
        { id: "priradit-plan", title: "Otvorte Čísla alebo IVR menu", text: "Pri správnej linke alebo voľbe vyberte uložený Plán zvonenia a uložte dané nastavenie. Skontrolujte aj aktívnosť skupín, linky a pracovný čas." },
        { id: "skusit-prijatie", title: "Dohodnite nový skúšobný hovor", text: "Najprv overte prijatie v prvom kroku. Potom samostatne overte neprijatie, druhý krok a posledné riešenie; zapojení kolegovia musia vedieť, že ide o skúšku." },
        { id: "skusit-pauzu", title: "Overte pauzu a nedostupnosť", text: "Skontrolujte, čo sa stane pri pauze jedného člena a keď v skupine nemôže prijať nikto.", result: "Viete vysvetliť, kto dostane ponuku, aké časy sa použijú a kde klient skončí. Prebiehajúci starší hovor nemusí použiť práve uložené zmeny." },
      ] },
    ], related: ["skupiny-zvonenia", "cisla-hodiny-a-ivr", "cakaren", "cesta-hovoru"], sources: ["src/components/dispatch/settings/RingPlanEditor.tsx", "src/components/dispatch/settings/ring-plan-model.ts", "src/server/telephony/routing/ring-plan.ts", "src/server/telephony/state/transitions.ts"],
  },
  {
    slug: "cisla-hodiny-a-ivr", title: "Čísla, otváracie hodiny a IVR", description: "Pripojte plán k telefónnej linke, nastavte pracovný čas a vysvetlite klientovi hlasové voľby.", categoryId: "nastavenia", audience: "manager", minutes: 9,
    keywords: ["číslo", "linka", "otváracie hodiny", "sviatok", "výnimka", "časové pásmo", "IVR", "klávesa", "hlasové menu", "nonstop"], prerequisites: ["Rola Manažér alebo Admin na ukladanie zmien.", "Existujúca telefónna linka a uložené plány, ktoré chcete použiť.", "Dohodnutý pracovný čas a text toho, čo má volajúci počuť."],
    sections: [
      { id: "nastavit-linku", title: "Priraďte smerovanie k existujúcemu číslu", steps: [
        { id: "vybrat-cislo", title: "Otvorte Nastavenia → Telefonovanie → Čísla", text: "Vyberte správne telefónne číslo. Skontrolujte jeho Štítok a prípadného Partnera; tieto informácie pomáhajú operátorovi pri prijatí." },
        { id: "overit-hlavnu-linku", title: "Skontrolujte Návrat na hlavnú linku", text: "Pri voľbe Vlastné smerovanie tejto linky posudzujte nastavenia danej linky. Pri návrate na inú linku treba preveriť aj hlášky a frontu vybranej hlavnej linky." },
        { id: "vybrat-vazby-linky", title: "Vyberte Plán zvonenia, IVR menu a Otváracie hodiny", text: "IVR je voliteľné. Bez neho ide hovor priamo na plán. Bez otváracích hodín sa linka z hľadiska pracovného času správa ako nonstop." },
        { id: "ulozit-linku", title: "Skontrolujte Linka je aktívna a Uložiť linku", text: "Prečítajte slovný súhrn smerovania pod formulárom, opravte chyby a uložte.", result: "Existujúce číslo používa uložené smerovanie. Nové číslo sa tým neobjednáva ani nevytvára." },
      ], screenshotIds: ["numbers"], note: { tone: "info", title: "Nové telefónne číslo rieši správca", text: "Obrazovka Čísla upravuje smerovanie existujúcej linky. Objednanie a pridanie nového čísla do systému je samostatná úloha správcu. Nastavenie Prostredie nemeňte bez dohody o účele linky." } },
      { id: "tyzdenny-rozvrh", title: "Vytvorte týždenné otváracie hodiny", steps: [
        { id: "pridat-rozvrh", title: "Otvorte Otváracie hodiny a Pridať rozvrh", text: "Zadajte názov a skontrolujte zobrazené Časové pásmo. Časy patria tomuto pásmu, nie automaticky pásmu počítača." },
        { id: "vyplnit-intervaly", title: "Doplňte intervaly pri dňoch", text: "Nastavte otvorenie a zatvorenie. Deň bez intervalu je zatvorený. Pri viacerých intervaloch skontrolujte prestávky a prípadné prekrytie." },
        { id: "ulozit-hodiny", title: "Skontrolujte Aktívne a Uložiť otváracie hodiny", text: "Prečítajte súhrn týždňa a aktuálneho stavu. Rozvrh potom vyberte pri príslušnej linke v Čísla.", result: "Priradená linka rešpektuje aktívny rozvrh; mimo otvorenia postupuje podľa riešenia pre zatvorenú prevádzku, vrátane ponuky spätného volania." },
      ], screenshotIds: ["hours"] },
      { id: "sviatky-a-vynimky", title: "Sviatky, výnimky a celý deň", paragraphs: ["Pre konkrétny deň použite Pridať výnimku, vyberte Dátum a Režim: Zatvorené celý deň alebo Otvorené inak. Pri inom otvorení doplňte príslušné intervaly a zrozumiteľný popis. Samotný názov sviatku v poznámke hodiny nemení.", "Ak má byť otvorené celý deň, použite ponúknutú voľbu celého dňa; zatvorenie o 23:59 by nechalo poslednú minútu dňa mimo otvorenia. Pri práci cez polnoc skontrolujte aj nasledujúci deň a výsledný súhrn rozvrhu."], note: { tone: "important", title: "Vypnutý rozvrh neznamená zatvorené", text: "Linka bez rozvrhu alebo s vypnutým rozvrhom zvoní nonstop z pohľadu otváracích hodín. Na zatvorenie konkrétneho dňa nastavte výnimku Zatvorené celý deň. Dostupnosť operátorov sa naďalej posudzuje samostatne." } },
      { id: "zostavit-ivr", title: "Vytvorte zrozumiteľné IVR menu", steps: [
        { id: "pridat-ivr-menu", title: "Otvorte IVR menu a Pridať menu", text: "Vyplňte Názov menu. Nastavte Čas na voľbu (s) a Prehratí menu podľa toho, koľko času má klient po dohratí oznámenia na rozhodnutie." },
        { id: "text-ivr", title: "Pripravte Nahrávka menu alebo Text namiesto nahrávky", text: "Text musí jasne hovoriť, ktorú klávesu stlačiť pre konkrétnu službu. Ak je nastavená nahrávka, text namiesto nahrávky sa nepoužije. Skontrolujte aj oznámenie pri neplatnej voľbe." },
        { id: "pridat-volbu-ivr", title: "Stlačte Pridať voľbu", text: "Vyberte Klávesa, vyplňte Názov voľby a určte Akcia. Pri Plán zvonenia vyberte cieľový plán, pri presmerovaní Cieľové číslo. Každá ponúkaná klávesa musí mať jednoznačný účel." },
        { id: "ulozit-ivr", title: "Použite Uložiť IVR menu a priraďte ho linke", text: "Po uložení otvorte Čísla, pri linke vyberte toto IVR menu a stlačte Uložiť linku.", result: "Noví volajúci na danej linke dostanú menu podľa jej účinného smerovania." },
      ], screenshotIds: ["ivr"] },
      { id: "akcie-ivr", title: "Čo môže klávesa v IVR vykonať", table: { headers: ["Akcia", "Čo nasleduje po voľbe klienta"], rows: [["Plán zvonenia", "Začne smerovanie podľa zvoleného plánu."], ["Spätné volanie", "Vytvorí sa požiadavka na spätné volanie a zaznie jej potvrdenie."], ["Presmerovanie na číslo", "Hovor pokračuje na určené povolené číslo."], ["Čakáreň", "Klient zostane na linke a čaká na operátora."], ["Zopakovať menu", "Klient si znova vypočuje možnosti."], ["Odkaz a ukončenie", "Prehrá sa príslušná hláška a hovor sa skončí."]] }, paragraphs: ["Pri IVR akcii Spätné volanie má následná nahrávka potvrdiť už uloženú požiadavku. Nemá žiadať ďalšie stlačenie klávesy. Voľba spätného hovoru počas čakania je iný krok, preto sa jej číslica ani text nemusia zhodovať s úvodným menu."] },
      { id: "overit-cestu-linky", title: "Po zmene overte viac ako jednu vetvu", bullets: ["Nový hovor v pracovnom čase a hovor mimo neho.", "Každú klávesu oznámenú v IVR vrátane zodpovedajúceho cieľa.", "Žiadnu voľbu, neplatnú klávesu a opakovanie menu.", "Cieľové plány, ich aktívnosť a dostupnosť zapojených skupín.", "Výnimku pre konkrétny dátum a časové pásmo.", "Text potvrdenia spätného volania a vznik položky v správnom zozname."], paragraphs: ["Pri vypnutom cieli IVR sa môže uplatniť pôvodný plán linky. Pred odovzdaním preto skontrolujte upozornenia pri plánoch aj pri menu. Zobrazený formulár opisuje nastavenie; výsledok potvrdí až dohodnutá skúška konkrétnej vetvy."] },
    ], related: ["cesta-hovoru", "plany-zvonenia", "hlasky-a-nahravanie", "spatne-hovory"], sources: ["src/components/dispatch/settings/NumbersPanel.tsx", "src/components/dispatch/settings/BusinessHoursEditor.tsx", "src/components/dispatch/settings/business-hours-model.ts", "src/components/dispatch/settings/IvrMenuEditor.tsx", "src/components/dispatch/settings/ivr-menu-model.ts", "src/server/telephony/state/transitions.ts"],
  },
  {
    slug: "hlasky-a-nahravanie", title: "Hlášky, jazyk a nahrávanie", description: "Upravte to, čo klient počuje, a rozlíšte oznámenie od skutočného zapnutia nahrávania.", categoryId: "nastavenia", audience: "manager", minutes: 7,
    keywords: ["hlášky", "jazyk", "hlas", "nahrávka", "nahrávanie", "prepis", "kvalita", "oznámenie", "hudba"], prerequisites: ["Rola Manažér alebo Admin na ukladanie zmien.", "Vybraná telefónna linka a dohodnuté znenie hlášok.", "Pri nastavení nahrávania údaje a rozhodnutia prevádzkovateľa požadované formulárom."],
    sections: [
      { id: "upravit-hlasky", title: "Vyberte linku a jazyk", steps: [
        { id: "otvorit-hlasky", title: "Otvorte Nastavenia → Telefonovanie → Hlášky a jazyk", text: "Vyberte Telefónna linka. Každá linka má vlastné hlášky a jazyk; pri návrate na hlavnú linku skontrolujte aj jej nastavenie." },
        { id: "vybrat-jazyk", title: "Vyberte Jazyk hovoru", text: "Rozhranie uvádza, ktorý jazyk je práve uložený a v ktorom jazyku upravujete texty. Dostupné sú slovenčina, čeština, angličtina a nemčina." },
        { id: "upravit-text-hlasky", title: "Nájdite situáciu v Knižnica hlášok", text: "Upravte text pre danú situáciu. Píšte stručne a povedzte klientovi konkrétnu možnosť: čakať, zvoliť klávesu alebo očakávať spätný hovor. Čísla a sľuby musia zodpovedať nastaveniu." },
      ], screenshotIds: ["announcements"] },
      { id: "vypocut-a-ulozit", title: "Vypočujte náhľad a uložte výsledok", steps: [
        { id: "vytvorit-hlas", title: "Podľa dostupnosti vytvorte hlasovú nahrávku", text: "Ak je generovanie pripojené, použite ovládanie pri hláške. Po zmene hlasu treba vytvoriť nahrávky znova. Ak generovanie nie je dostupné, používané texty bez nahrávky prečíta telefónny hlas." },
        { id: "vypocut-hlasku", title: "Použite Vypočuť hlášku", text: "Overte výslovnosť, jazyk, zrozumiteľnosť a správne klávesy. Dĺžka uvedená v rozhraní je orientačná." },
        { id: "ulozit-hlasky", title: "Stlačte Uložiť hlášky a jazyk", text: "Počkajte na Nastavenia sú uložené. Prepnutie linky či prehratie náhľadu nenahrádza uloženie.", result: "Zvolený jazyk a používané hlášky sa uplatnia pre nové hovory podľa konkrétnej situácie." },
      ] },
      { id: "pripravena-hlaska", title: "Pripravená hláška ešte nemusí zaznieť", paragraphs: ["Knižnica rozlišuje hlášky zapojené do hovorov a pripravené hlášky. Pripravenú hlášku môžete upraviť, vypočuť a uložiť vopred; tým sa jej použitie v hovore samo nezapne.", "Rovnako uloženie textu „hovor je nahrávaný“ nezapína nahrávanie. Prehrávanie závisí od situácie, povolených funkcií a nastavenia. Po uložení skúšajte konkrétnu vetvu hovoru, v ktorej má daná hláška zaznieť."] },
      { id: "politika-nahravania", title: "Skutočné nahrávanie nastavujete osobitne", paragraphs: ["Nastavenia → Telefonovanie → Nahrávanie a kvalita určuje, či sa hovory nahrávajú a či sa pripravuje prepis, AI súhrn alebo návrh hodnotenia. Táto časť ukazuje aj Pripravenosť zapojenia; uložená voľba nemusí znamenať, že je všetko technicky pripravené."], steps: [
        { id: "vybrat-rozsah-nahravania", title: "Skontrolujte rozsah", text: "Podľa schváleného postupu prevádzky nastavte Nahrávať hovory a rozsah Prichádzajúce hovory / Odchádzajúce hovory. Prepis potrebuje nahrávanie, AI súhrn prepis a návrh hodnotenia AI analýzu." },
        { id: "doplnit-udaje-nahravania", title: "Vyplňte údaje prevádzkovateľa a uchovanie", text: "Doplňte požadované kontakty, informácie pre účastníkov, účely a lehoty podľa rozhodnutia prevádzkovateľa. Vzorové texty nenahrádzajú jeho vlastné údaje." },
        { id: "ulozit-nahravanie", title: "Prečítajte požadované potvrdenie a uložte", text: "Skontrolujte súlad s hláškami linky. Ak je všetko pripravené a formulár vyžaduje potvrdenie správnosti, potvrďte ho a použite Uložiť nahrávanie a kvalitu.", result: "Rozhranie zobrazí uloženú verziu alebo dôvod, prečo zmena nemôže byť použitá." },
      ], screenshotIds: ["recording"] },
      { id: "nahravanie-v-hovore", title: "Čo sledovať pri konkrétnom hovore", paragraphs: ["Pri hovore sledujte zobrazený stav nahrávania a dostupné ovládanie. Chýbajúca nahrávka môže súvisieť s rozsahom, pripravenosťou, konkrétnym priebehom alebo limitom; z textu hlášky ju nemožno vyvodiť.", "V Hlášky a jazyk je aj prepínač Hlášky o zmenách nahrávania pre oznámenie vypnutia a obnovenia. Jeho vypnutie samo nevypína úvodný oznam ani politiku nahrávania.", "Vypnutie nového nahrávania neodstraňuje staršie záznamy. Ich dostupnosť riadia oprávnenia a uchovanie. Prepis, súhrn a návrh hodnotenia treba posúdiť v kontexte hovoru; automatický návrh nie je konečné rozhodnutie o práci operátora."] },
    ], related: ["cisla-hodiny-a-ivr", "plany-zvonenia", "reporty-a-pouzivatelia"], sources: ["src/components/dispatch/settings/AnnouncementsPanel.tsx", "src/components/dispatch/settings/RecordingPolicyPanel.tsx", "src/components/dispatch/PhoneBar.tsx", "src/components/dispatch/settings/announcements-model.ts"],
  },
  ...guideOperationsChapters,
];
