import type { GuideChapter } from "./types";

export const guideOperationsChapters: GuideChapter[] = [
  {
    slug: "dochadzka", title: "Dochádzka a odovzdanie služby",
    description: "Pozrite si svoje smeny, požiadajte o neprítomnosť a odovzdajte kolegovi rozpracovanú prácu.",
    categoryId: "prevadzka", audience: "all", minutes: 6,
    keywords: ["smena", "služba", "dochádzka", "plánovanie", "dovolenka", "neprítomnosť", "odovzdanie"],
    prerequisites: ["Ste prihlásený pod vlastným účtom. Plán smien a schvaľovanie žiadostí spravuje manažér alebo administrátor."],
    sections: [
      { id: "moja-dochadzka", title: "Kedy máte naplánovanú službu", paragraphs: ["Otvorte Menu → Dochádzka → Moja dochádzka. Skontrolujte zobrazené meno, dni a časy smien. Prehľad obsahuje plánované hodiny, publikované alebo potvrdené smeny a údaje o dovolenke."], screenshotIds: ["attendance"], note: { tone: "important", title: "Smena a dostupnosť telefónu sú odlišné", text: "Naplánovaná smena vás sama nenastaví na Dostupný. Pred prijímaním hovorov skontrolujte telefón a vedome sa nastavte dostupný. Rovnako koniec naplánovanej smeny nenahrádza odovzdanie práce a odhlásenie." } },
      { id: "ziadost-o-nepritomnost", title: "Ako požiadať o neprítomnosť", steps: [
        { id: "vybrat-typ-ziadosti", title: "Vyplňte Novú žiadosť", text: "V Mojej dochádzke vyberte druh neprítomnosti, prvý a posledný deň. Doplňte požadované údaje a dôvod podľa typu žiadosti." },
        { id: "odoslat-ziadost", title: "Stlačte Odoslať žiadosť", text: "Pred odoslaním skontrolujte dátumy aj zobrazeného pracovníka.", result: "Žiadosť sa po úspešnom odoslaní zobrazí medzi Mojimi žiadosťami." },
        { id: "sledovat-schvalenie", title: "Skontrolujte rozhodnutie", text: "Odoslanie žiadosti nie je jej schválenie. Sledujte stav a pri nejasnosti sa dohodnite s vedúcim." },
      ] },
      { id: "planovanie-pre-veduceho", title: "Naplánovanie smien pre vedúceho", steps: [
        { id: "zacat-plan-smien", title: "Otvorte Plánovanie → Naplánovať smeny", text: "Vyberte jeden deň, viac dní alebo rozsah. Tlačidlom Ďalej prejdite na výber typu a času smien." },
        { id: "priradit-ludi", title: "Priraďte ľudí", text: "V kroku Ľudia vyberte dispečerov. Skontrolujte súbehy a upozornenia na dostupnosť." },
        { id: "skontrolovat-publikovat", title: "Skontrolujte a publikujte", text: "V kroku Kontrola a publikovanie prejdite obsadenie, časy a konflikty. Uložiť koncept zachová rozpracovaný plán; Publikovať plán ho zverejní ako platný plán služby.", result: "Po úspechu sa zobrazí potvrdenie publikovania. Pred odchodom skontrolujte, že je plán viditeľný v kalendári." },
      ], note: { tone: "info", title: "Schvaľovanie žiadostí", text: "Manažér alebo admin otvorí Žiadosti a posúdi konkrétnu neprítomnosť. V aktuálnom rozhraní môžu byť rozhodovacie tlačidlá označené Approve (schváliť) a Decline (zamietnuť). Rozhodnutie si overte podľa výsledného stavu žiadosti." } },
      { id: "odovzdanie-sluzby", title: "Ako odovzdať rozpracovanú službu", bullets: ["Pri každom otvorenom prípade doplňte posledný dohodnutý krok, zodpovednú osobu a čo sa ešte čaká od klienta alebo techniky.", "Prácu s termínom odovzdajte cez úlohu konkrétnemu kolegovi. Samotné odloženie upozornenia nemení zodpovednosť za úlohu.", "Prejdite čakáreň aj požiadavky na spätné volanie. Klient čakajúci na linke potrebuje okamžité odovzdanie.", "Skontrolujte uloženie rozpracovaných údajov, dokončite alebo odovzdajte aktívny hovor a odhláste sa z telefónie. Pri striedaní na rovnakom počítači sa odhláste aj z aplikácie."], note: { tone: "important", title: "Odovzdanie musí mať príjemcu", text: "Poznámka, že prípad preberie kolega, sama nezaručí jeho prevzatie. Dohodnite si, kto zodpovednosť preberá, a skontrolujte priradenie prípadu alebo úlohy." } },
    ], related: ["priprava-na-sluzbu", "pauza-a-zastupovanie", "ulohy-a-poznamky"],
    sources: ["src/components/dispatch/AttendanceModule.tsx", "src/app/api/attendance/shifts/route.ts", "src/components/dispatch/TaskWorkspacePanel.tsx"],
  },
  {
    slug: "flotila-a-adresar", title: "Flotila a adresár",
    description: "Nájdite vhodné vozidlo, posúďte aktuálnosť údajov a vyhľadajte kontakty na pomoc zákazníkovi.",
    categoryId: "prevadzka", audience: "all", minutes: 6,
    keywords: ["flotila", "odťahovka", "náhradné vozidlo", "GPS", "poloha", "adresár", "kontakt", "firma", "pobočka", "asistencia"],
    prerequisites: ["Máte prístup do aplikácie. Úpravy adresára a niektoré nastavenia vozidiel vyžadujú oprávnenie vedúceho."],
    sections: [
      { id: "vyhladanie-vozidla", title: "Ako nájsť vozidlo", steps: [
        { id: "otvorit-flotilu", title: "Otvorte Menu → Flotila", text: "Vyberte Náhradné vozidlá alebo Odťahovky podľa potrebnej služby. Prejdite stav, pobočku a základné údaje vozidla." },
        { id: "otvorit-detail-vozidla", title: "Otvorte vozidlo kliknutím na názov", text: "V detaile skontrolujte jeho parametre, prípadnú posádku, kontakt, doklady a informácie o obsadení." },
        { id: "overit-vhodnost", title: "Overte vhodnosť pre konkrétny zásah", text: "Porovnajte vozidlo s požiadavkami klienta a miestom zásahu. Ak sú údaje neoverené alebo zastarané, potvrďte dostupnosť s príslušným kolegom pred prísľubom klientovi.", result: "Máte vybranú a overenú techniku; jej priradenie k zásahu dokončite v príslušnom prípade." },
      ], screenshotIds: ["fleet"] },
      { id: "aktualnost-flotily", title: "Poloha neznamená voľné vozidlo", table: { headers: ["Údaj", "Ako ho čítať"], rows: [
        ["Dostupnosť a obsadenie", "Hovorí o použití vozidla. Skontrolujte stav a aktuálnosť zdroja."],
        ["GPS poloha", "Posledné známe miesto vozidla. Vždy sledujte čas pozorovania."],
        ["Neoverené / zastarané", "Údaje nestačia na spoľahlivé potvrdenie dostupnosti. Neznamenajú automaticky voľné vozidlo."],
        ["Doklady", "Upozornenie na blížiaci sa termín alebo potrebnú kontrolu. Pred nasadením vyriešte nejasnosti s vedúcim."],
      ] }, paragraphs: ["Obnoviť všetky zdroje vyžiada novšie údaje, ale samo nevyrieši chýbajúci signál GPS ani neúplné párovanie. Čas obnovy a čas samotnej polohy môžu byť odlišné."] },
      { id: "najst-kontakt", title: "Ako vyhľadať kontakt", steps: [
        { id: "otvorit-adresar", title: "Otvorte Nastavenia → Adresár", text: "Vyhľadajte časť názvu firmy, meno, telefón alebo e-mail. Podľa potreby zúžte typ záznamu." },
        { id: "skontrolovat-adresar-filtre", title: "Skontrolujte stav a súvislosti", text: "Ak kontakt nevidíte, skontrolujte filtre Aktívne záznamy, Archivované alebo Všetky stavy. Otvorte detail a overte prepojenú firmu či pobočku." },
        { id: "pouzit-kontakt", title: "Použite overený kontakt", text: "Pred volaním skontrolujte číslo a osobu, ktorú chcete kontaktovať. Telefonovanie vyžaduje pripravený telefón; otvorenie záznamu samo hovor nezačne." },
      ], screenshotIds: ["directory"] },
      { id: "sprava-adresara", title: "Pridanie alebo oprava záznamu", paragraphs: ["Používateľ s oprávnením na úpravy použije Pridať záznam alebo v detaile Upraviť záznam. Vyberte správny typ, doplňte názov a kontakty, skontrolujte väzby a stlačte Uložiť záznam. Chyby pri poliach treba opraviť pred opätovným uložením."], bullets: ["Pre osobný kontakt doplňte aspoň použiteľný telefón alebo e-mail.", "Nepoužívaný záznam presuňte cez Do archívu; v detaile archivovaného záznamu ho možno Obnoviť z archívu.", "Prevziať z prípadov slúži na doplnenie asistenčných spoločností používaných v prípadoch. Najprv skontrolujte, či už hľadaný záznam v adresári nie je."], note: { tone: "info", title: "Zmeny sú spoločné", text: "Úprava kontaktu alebo interných údajov vozidla ovplyvní aj ostatných používateľov. Chybné párovanie vozidiel rieši vedúci po kontrole identity vozidla; chýbajúca poloha sama nie je dôvod na prepárovanie." } },
    ], related: ["pripad", "mapa-a-sms", "prijatie-a-zacatie-hovoru"],
    sources: ["src/components/dispatch/FleetModule.tsx", "src/components/dispatch/settings/DirectoryPanel.tsx", "src/components/dispatch/settings/DirectoryEntryDialog.tsx"],
  },
  {
    slug: "reporty-a-pouzivatelia", title: "Reporty, dohľad a používatelia",
    description: "Zorientujte sa vo výsledkoch prevádzky a v možnostiach správy prístupu kolegov.",
    categoryId: "prevadzka", audience: "all", minutes: 6,
    keywords: ["report", "štatistika", "kvalita", "operátor", "používateľ", "pozvánka", "oprávnenia", "wallboard"],
    prerequisites: ["Reporty môžu používať aj dispečeri. Správa účtov a dohľad majú osobitné oprávnenia."],
    sections: [
      { id: "otvorenie-reportov", title: "Ako zobraziť prehľad", steps: [
        { id: "vybrat-report-obdobie", title: "Otvorte Menu → Reporty a vyberte obdobie", text: "Použite Dnes, 7 dní alebo 30 dní. Pri porovnávaní čísel sa vždy uistite, že používate rovnaké obdobie." },
        { id: "vybrat-report-oblast", title: "Vyberte oblasť reportu", text: "Prehľad sumarizuje prevádzku. Ďalšie záložky sú Hovory, Kvalita, Operátori a Prípady." },
        { id: "posudit-report", title: "Pozrite sa na ukazovateľ aj jeho kontext", text: "Pri neobvyklom výsledku prejdite súvisiace hovory alebo prípady. Ak sa zobrazuje chyba načítania, nepovažujte chýbajúce údaje za nulovú aktivitu." },
      ], screenshotIds: ["reports"] },
      { id: "vyklad-ukazovatelov", title: "Čomu venovať pozornosť", bullets: ["Čakanie pred spojením nie je dĺžka rozhovoru s operátorom.", "Neprijatý hovor a výslovná požiadavka klienta na spätné zavolanie sú odlišné situácie.", "Volajúci môže čakanie ukončiť skôr, než sa spojí s dispečerom. Pri hodnotení výsledku si overte priebeh hovoru.", "Chýbajúce hodnotenie kvality neznamená zlý hovor. Výsledok nemusí byť ešte dostupný alebo pre daný hovor nevznikol.", "Výsledky používajte spolu s kontextom prípadu a priebehom hovoru; samotné číslo nevysvetľuje všetky okolnosti."] },
      { id: "dohlad", title: "Wallboard a dohľad počas hovoru", paragraphs: ["Wallboard je samostatná prehľadová obrazovka pre oprávnené roly. Poskytuje rýchlu orientáciu v prevádzke; nenahrádza vybavenie úloh a hovorov v aplikácii.", "Dohľad nad hovorom je vyhradený manažérovi a administrátorovi. Riaďte sa možnosťami zobrazenými pri konkrétnom hovore a pravidlami vašej organizácie. Dostupnosť dohľadu a jeho režim závisia aj od stavu hovoru."], note: { tone: "info", title: "Roly majú rozdielne možnosti", text: "Prístup k reportom neznamená prístup ku všetkým správcovským akciám. Ak akciu nevidíte alebo sa odmietne, overte oprávnenie s administrátorom." } },
      { id: "novy-pouzivatel", title: "Pridanie kolegu — manažér alebo admin", steps: [
        { id: "otvorit-pouzivatelov", title: "Otvorte Nastavenia → Používatelia", text: "V časti Nový používateľ vyplňte meno, pracovný e-mail a primeranú rolu. Manažér spravuje dispečerské roly; admin má širšie oprávnenia." },
        { id: "poslat-pristup", title: "Vyberte spôsob odovzdania prístupu", text: "Voľba Poslať prístup hneď po vytvorení odošle kolegovi prístupový e-mail. Skontrolujte adresu ešte pred vytvorením účtu." },
        { id: "overit-ucet", title: "Skontrolujte nový účet v zozname", text: "V Existujúcich používateľoch overte meno, e-mail, rolu a stav. Podľa potreby použite Poslať prístup alebo Preposlať prístup.", result: "Kolega dostane odkaz na nastavenie svojho hesla. Prístupový e-mail nenahrádza jeho prvé prihlásenie a pripravenie telefónu." },
      ] },
      { id: "udrzba-uctov", title: "Oprava prístupu a vlastné heslo", paragraphs: ["V existujúcom účte opravte údaje a stlačte Uložiť. Reset hesla odošle postup obnovy príslušnému používateľovi. Deaktivovať vypne prístup; Reaktivovať ho znova povolí podľa stavu účtu.", "V časti Moje heslo meníte heslo práve prihláseného používateľa, nie heslo kolegu otvoreného v zozname. Zadajte a zopakujte nové heslo."], note: { tone: "important", title: "Vymazanie účtu patrí administrátorovi", text: "Vymazať účet je iná operácia než dočasne deaktivovať prístup. Pred vymazaním vyriešte odovzdanie práce a overte, že je zvolený správny účet." } },
    ], related: ["prihlasenie", "dochadzka", "spatne-hovory", "hlasky-a-nahravanie"],
    sources: ["src/components/dispatch/ReportDashboard.tsx", "src/components/dispatch/UserAccessSettings.tsx", "src/server/access-policy.ts", "src/app/wallboard/page.tsx", "src/lib/telephony/supervisor-mode.ts"],
  },
  {
    slug: "riesenie-problemov", title: "Riešenie bežných problémov",
    description: "Začnite tým, čo vidíte na obrazovke. Overte stav a pokračujte konkrétnym postupom.",
    categoryId: "pomoc", audience: "all", minutes: 8,
    keywords: ["pomoc", "chyba", "nefunguje", "nezvoní", "nepočujem", "mikrofón", "iné okno", "neuložené", "konflikt", "upozornenie", "heslo"],
    prerequisites: ["Pri riešení problému si všimnite presný text hlášky a či práve prebieha hovor."],
    sections: [
      { id: "nezvoni-telefon", title: "Telefón mi nezvoní", steps: [
        { id: "skontrolovat-stav-telefonu", title: "Skontrolujte pripojenie telefónu", text: "V hlavičke otvorte stav telefónu. Pri odpojení ho pripojte podľa ponúknutej akcie. Hláška Telefónia nie je nakonfigurovaná vyžaduje kontrolu správcom." },
        { id: "skontrolovat-dostupnost", title: "Skontrolujte vlastnú dostupnosť", text: "Ak ste na pauze alebo odhlásený z telefónie, po pripravení použite Som dostupný. Počas iného hovoru alebo dopisovania vám systém nemusí ponúknuť nový hovor." },
        { id: "skontrolovat-miesto-zvonenia", title: "Skontrolujte, kde máte prijímať hovory", text: "V Môj telefón overte prijímanie cez aplikáciu alebo osobný mobil. Ak je zvolený mobil, pozrite jeho signál a zvonenie. Pri hláške Iné okno skontrolujte ďalšie otvorené okno aplikácie." },
        { id: "skontrolovat-skupinu", title: "Požiadajte vedúceho o kontrolu smerovania", text: "Ak pripojenie aj dostupnosť vyzerajú správne, vedúci overí členstvo v skupine, priradenie plánu k číslu, pracovný čas a poradie krokov. Byť členom skupiny neznamená, že vám zazvoní každý hovor." },
      ], note: { tone: "important", title: "Obnovenie stránky počas hovoru môže hovor prerušiť", text: "Pred obnovou alebo zatvorením okna dokončite hovor a skontrolujte uloženie práce. Ak sa problém týka iba zvuku, začnite výberom zariadenia a kontrolou mikrofónu." } },
      { id: "problemy-so-zvukom", title: "Klient ma nepočuje alebo nepočujem ja jeho", table: { headers: ["Situácia", "Čo skontrolovať"], rows: [
        ["Klient ma nepočuje", "Či nie je stlmený mikrofón, či má stránka povolenie používať mikrofón a či je zvolený správny vstup v zariadení."],
        ["Ja nepočujem klienta", "Hlasitosť zariadenia, pripojené slúchadlá a zvolený výstup zvuku. Zvuk môže smerovať do iného zariadenia."],
        ["Zvuk ide zo starých slúchadiel", "V Môj telefón skontrolujte dostupný výstup. Po odpojení zariadenia overte, ktorý výstup zostal zvolený."],
        ["Hovor sa prerušuje", "Kvalitu internetového pripojenia a stav telefónu. Zapíšte čas problému a odovzdajte ho vedúcemu."],
      ] }, paragraphs: ["Povolenie oznámení a povolenie mikrofónu sú dve rôzne nastavenia prehliadača. Zapnuté upozornenia samy mikrofón nepovolia."] },
      { id: "ine-okno", title: "Zobrazuje sa Iné okno", paragraphs: ["Telefón môže byť pripojený v inom okne alebo na inom zariadení. Najprv skontrolujte, či tam neprebieha hovor. Keď je bezpečné pokračovať v aktuálnom okne, použite ponúknutú akciu Prevziať telefón do tohto okna a overte nový stav pripojenia.", "Otvorenie návodu v ďalšej karte samo ďalší telefón nepripája. Ak vidíte Iné okno, skontrolujte najmä ďalšie okno samotnej dispečerskej aplikácie."] },
      { id: "nemozem-prevziat", title: "Nemôžem prevziať hovor", paragraphs: ["Prečítajte vysvetlenie priamo pri tlačidle. Najprv pripoj telefón upozorňuje na pripojenie; Najprv sa nastav dostupný na dostupnosť. Pri Pripájanie hovoru… už môže prebiehať pripájanie a ďalšie kliknutie nepomôže.", "Prijať patrí ku konkrétnej ponuke hovoru. Prevziať v čakárni znamená prevziať čakajúci hovor; Prevziať pri spätnom volaní znamená prevziať požiadavku na neskoršie vybavenie. Hovor si medzitým mohol prevziať kolega."], note: { tone: "info", title: "Anonymné alebo nepoužiteľné číslo", text: "Pri spätnom volaní môže byť potrebné potvrdiť overené náhradné číslo. Ak použiteľné číslo chýba, nevymýšľajte ho a neoznačujte požiadavku za vybavenú len preto, že sa nedá zavolať." } },
      { id: "neulozene-zmeny", title: "Údaje sa neuložili alebo ich zmenil kolega", steps: [
        { id: "precitat-chybu-ulozenia", title: "Prečítajte stav uloženia", text: "Pri existujúcom prípade sledujte automatické uloženie. Nový prípad, úloha a osobná poznámka majú vlastnú ukladaciu akciu. Zatvorenie formulára nie je dôkaz uloženia." },
        { id: "opravit-ulozenie", title: "Opravte chybné polia alebo obnovte spojenie", text: "Ak sú pri poliach chyby, opravte ich. Pri výpadku ponechajte rozpracované okno otvorené a skúste uloženie po obnovení spojenia." },
        { id: "vyriesit-konflikt", title: "Pri súbežnej zmene porovnajte aktuálne údaje", text: "Ak hláška upozorňuje na zmenu kolegom, načítajte aktuálnu verziu cez ponúknutú akciu a skontrolujte rozdiel. Pri dôležitom texte si pred tým odložte jeho kópiu. Zmeny neprepisujte naslepo.", result: "Pokračujte až po potvrdení úspešného uloženia a kontrole výsledných údajov." },
      ] },
      { id: "chyba-upozorneni-a-pristupu", title: "Neprišlo upozornenie alebo chýba oprávnenie", bullets: ["V Nastavenia → Upozornenia skontrolujte zapnutie na tomto zariadení, vybrané typy a zvuk. Povolenie v jednom prehliadači neznamená povolenie vo všetkých zariadeniach.", "Kliknutie na upozornenie o hovore otvorí aplikáciu; hovor treba prijať v nej.", "Ak vidíte obrazovku, ale nemôžete uložiť zmenu, môže ísť o obmedzenie roly. Požiadajte vedúceho o overenie oprávnenia.", "Pri probléme s prihlásením použite Zabudnuté heslo a skontrolujte e-mail účtu. Opakované zakladanie účtu nie je riešením neplatného hesla."] },
      { id: "co-odovzdat-podpore", title: "Čo poslať vedúcemu pri nevyriešenom probléme", bullets: ["Čas udalosti a názov linky alebo číslo prípadu.", "Čo ste chceli urobiť, čo ste stlačili a presné znenie hlášky.", "Či bol telefón dostupný, na pauze, na hovore alebo v inom okne.", "Typ zariadenia a prehliadač. Screenshot hlášky môže pomôcť; vynechajte heslá a nepotrebné osobné údaje."] },
    ], related: ["priprava-na-sluzbu", "moj-telefon", "pauza-a-zastupovanie", "spatne-hovory", "prihlasenie"],
    sources: ["src/components/dispatch/HeaderPhoneStatusMenu.tsx", "src/components/dispatch/MyPhonePanel.tsx", "src/components/dispatch/phone-bar-model.ts", "src/components/dispatch/CaseDetail.tsx", "src/components/pwa/PushNotificationSettings.tsx"],
  },
  {
    slug: "slovnik-a-kontrolne-zoznamy", title: "Slovník a kontrolné zoznamy",
    description: "Pojmy telefonovania jednoduchou rečou a kontrola krokov pri najčastejších pracovných situáciách.",
    categoryId: "pomoc", audience: "all", minutes: 5,
    keywords: ["slovník", "checklist", "kontrola", "linka", "skupina", "krok", "IVR", "fronta", "callback", "dopisovanie"],
    prerequisites: [],
    sections: [
      { id: "telefonicky-slovnik", title: "Čo znamenajú jednotlivé pojmy", table: { headers: ["Pojem", "Význam v aplikácii"], rows: [
        ["Linka / telefónne číslo", "Číslo, na ktoré volá zákazník, alebo linka zvolená pre odchádzajúce volanie."],
        ["Skupina zvonenia", "Zoznam operátorov alebo externých čísel, ktorým možno ponúknuť hovor."],
        ["Plán zvonenia", "Usporiadané kroky a riešenie pre prípad, že nikto hovor neprijme."],
        ["Krok", "Jedna skupina v pláne s určeným spôsobom a časom zvonenia."],
        ["Všetkým naraz", "Členovia, ktorí sú oprávnení dostať ponuku a zmestia sa do kapacity, zvonia súčasne."],
        ["Postupne", "Členovia skupiny sa skúšajú po poradí. Čas sa môže uplatňovať na každého člena osobitne."],
        ["IVR menu", "Hlasové menu, v ktorom volajúci vyberá možnosť stlačením číslice na telefóne."],
        ["Čakáreň / fronta", "Volajúci zostáva na linke a čaká na obsluhu; môže tu byť aj odložený hovor."],
        ["Spätné volanie / callback", "Požiadavka alebo úloha kontaktovať zákazníka neskôr. Nie je to živý hovor v čakárni."],
        ["Dopisovanie", "Čas po hovore na doplnenie údajov pred ďalšou automatickou ponukou."],
        ["Pauza", "Vedomé prerušenie automatického prijímania pracovných hovorov; pri návrate treba obnoviť dostupnosť."],
        ["Konzultácia", "Kontaktovanie kolegu pred dokončením prepojenia hovoru."],
        ["Náhradné riešenie", "Čo má nasledovať po neúspešnom pláne: napríklad čakáreň alebo ponuka spätného volania."],
      ] } },
      { id: "kontrola-pred-sluzbou", title: "Pred začiatkom služby", bullets: ["Som prihlásený pod vlastným menom.", "Mám vybraný správny spôsob prijímania hovorov a odchádzajúcu linku.", "Telefón je pripojený, mikrofón povolený a zvuk ide do správneho zariadenia.", "Som Dostupný; naplánovaná smena sama tento stav nenahrádza.", "Prešiel som odovzdané prípady, úlohy, čakáreň a spätné hovory."] },
      { id: "kontrola-pauzy", title: "Pred pauzou a po návrate", bullets: ["Dokončil alebo odovzdal som aktuálny hovor.", "Vybral som dôvod a spôsob pauzy. Pri zastupovaní viem, ktorý kolega ma má zastúpiť.", "Skontroloval som potvrdenie pauzy. Počas pauzy neočakávam automatické pracovné hovory ani na osobnom mobile.", "Po návrate som zvolil Som dostupný a skontroloval stav telefónu. Pripomienka sama pauzu neukončuje."] },
      { id: "kontrola-pripadu", title: "Pred odovzdaním alebo uzavretím prípadu", bullets: ["Kontakty, vozidlo, miesto a dohodnutá pomoc sú správne.", "Je jasné, kto rieši nasledujúci krok a dokedy.", "Potrebné úlohy, komunikácia a prílohy sú pripojené k správnemu prípadu.", "Uloženie je potvrdené. Stav zodpovedá tomu, čo sa skutočne stalo.", "Ak zostáva spätné volanie alebo iná otvorená práca, má svojho zodpovedného človeka."] },
      { id: "kontrola-planu", title: "Po zmene plánu zvonenia — vedúci", bullets: ["Skupina obsahuje správnych členov v správnom poradí.", "Každý krok má správnu skupinu, spôsob zvonenia a čas. Pri postupnom zvonení som skontroloval aj čas každého člena.", "Je nastavené riešenie, keď nikto nezdvihne.", "Plán je aktívny a je priradený k správnej linke alebo voľbe IVR.", "Pracovný čas, výnimky a hlášky zodpovedajú požadovanému postupu.", "Zmeny sa uložili. Na dohodnutom skúšobnom hovore sa overí prijatie aj neprijatie; rozbehnutý hovor môže mať ešte pôvodný plán."] },
    ], related: ["cesta-hovoru", "plany-zvonenia", "priprava-na-sluzbu", "dochadzka"],
    sources: ["src/components/dispatch/settings/ring-plan-model.ts", "src/components/dispatch/settings/ring-groups-model.ts", "src/components/dispatch/my-phone-model.ts", "src/components/dispatch/PauseRoutingDialog.tsx"],
  },
];
